import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { db } from "./db";
import { consumeRateLimit } from "./security";

export const API_SCOPES = ["projects:read","issues:read","issues:write","comments:read","comments:write","sprints:read","sprints:write","users:read","releases:read","releases:write"] as const;
export type ApiScope = typeof API_SCOPES[number];
export function hashSecret(value:string){return createHash("sha256").update(value).digest("hex")}
export function createApiSecret(){const prefix=randomBytes(6).toString("hex");const secret=randomBytes(32).toString("base64url");return{prefix,secret:`pln_${prefix}.${secret}`,secretHash:hashSecret(`pln_${prefix}.${secret}`)}}
export function apiError(status:number,code:string,message:string,requestId?:string){return NextResponse.json({error:{code,message,requestId}}, {status,headers:{"cache-control":"no-store"}})}

export async function authenticateApi(request:Request,scope:ApiScope){const requestId=request.headers.get("x-request-id")?.slice(0,100)??crypto.randomUUID();const header=request.headers.get("authorization")??"";if(!header.startsWith("Bearer "))return{error:apiError(401,"unauthorized","A bearer API token is required.",requestId)};const secret=header.slice(7);const match=/^pln_([a-f0-9]{12})\./.exec(secret);if(!match)return{error:apiError(401,"unauthorized","The API token is invalid.",requestId)};const token=await db.apiToken.findUnique({where:{prefix:match[1]},include:{createdBy:{include:{memberships:true,projectRoles:true}},workspace:true}});const expected=token?Buffer.from(token.secretHash,"hex"):Buffer.alloc(32);const actual=Buffer.from(hashSecret(secret),"hex");if(!token||expected.length!==actual.length||!timingSafeEqual(expected,actual)||token.revokedAt||token.expiresAt&&token.expiresAt<=new Date())return{error:apiError(401,"unauthorized","The API token is invalid or expired.",requestId)};if(!token.scopes.includes(scope))return{error:apiError(403,"insufficient_scope",`The ${scope} scope is required.`,requestId)};const membership=token.createdBy.memberships.find(item=>item.workspaceId===token.workspaceId&&!item.deactivatedAt);if(!membership)return{error:apiError(403,"inactive_actor","The token owner no longer has workspace access.",requestId)};const rate=await consumeRateLimit(`api:${token.id}`,Number(process.env.API_RATE_LIMIT??120),60);if(!rate.allowed)return{error:apiError(429,"rate_limited","API rate limit exceeded.",requestId)};await db.apiToken.update({where:{id:token.id},data:{lastUsedAt:new Date()}});return{token,requestId,workspaceId:token.workspaceId,userId:token.createdById,workspaceRole:membership.role,rate};}

export function tokenProjectWhere(auth:{workspaceId:string;userId:string;workspaceRole:string}){return{workspaceId:auth.workspaceId,archivedAt:null,...(auth.workspaceRole==="OWNER"||auth.workspaceRole==="ADMIN"?{}:{OR:[{visibility:"PUBLIC" as const},{members:{some:{userId:auth.userId}}}]})}}
export function pagination(request:Request){const params=new URL(request.url).searchParams;const limit=Math.min(100,Math.max(1,Number(params.get("limit"))||50));const cursor=params.get("cursor")||undefined;return{limit,cursor}}
export function page<T extends{id:string}>(items:T[],limit:number){const hasMore=items.length>limit;const data=items.slice(0,limit);return{data,page:{limit,nextCursor:hasMore?data.at(-1)?.id??null:null}}}
export async function idempotency(request:Request,tokenId:string,route:string){const key=request.headers.get("idempotency-key")?.trim();if(!key||key.length>128)return{error:apiError(400,"idempotency_key_required","A 1–128 character Idempotency-Key is required.")};const existing=await db.apiIdempotency.findUnique({where:{tokenId_key_route:{tokenId,key,route}}});return{key,existing}}
