const sensitiveKey = /(password|credential|secret|token|cookie|authorization|content|body)/i;
export function redactAuditMetadata(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(redactAuditMetadata);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, sensitiveKey.test(key) ? "[REDACTED]" : redactAuditMetadata(item)]));
}

import { createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual } from "node:crypto";
import { mkdir,readFile,writeFile } from "node:fs/promises";import path from "node:path";import { db } from "./db";
const exportRoot=path.resolve(/* turbopackIgnore: true */ process.env.AUDIT_EXPORT_ROOT??"/app/storage/audit-exports");
function exportKey(){return createHash("sha256").update(process.env.AUDIT_EXPORT_KEY??process.env.SESSION_SECRET??"docker-development-secret-change-before-production").digest()}
export async function verifyAuditChain(workspaceId:string){const rows=await db.$queryRaw<Array<{id:string;sequence:bigint;eventHash:string;expectedHash:string;previousHash:string|null;expectedPrevious:string|null}>>`SELECT e.id,e.sequence,e."eventHash",encode(digest(concat_ws('|',e."workspaceId",e.sequence,COALESCE(e."previousHash",''),e."keyVersion",e.id,COALESCE(e."actorId",''),e.action,e."targetType",COALESCE(e."targetId",''),COALESCE(e.metadata::text,'null'),e."createdAt"::text),'sha256'),'hex') AS "expectedHash",e."previousHash",lag(e."eventHash") OVER(ORDER BY e.sequence) AS "expectedPrevious" FROM "AuditEvent" e WHERE e."workspaceId"=${workspaceId} ORDER BY e.sequence`;const anchor=await db.auditChainAnchor.findUnique({where:{workspaceId}});const broken=rows.filter((row,index)=>row.eventHash!==row.expectedHash||index===0&&(row.sequence!==(anchor?.sequence??0n)+1n||row.previousHash!==(anchor?.eventHash??null))||index>0&&row.previousHash!==row.expectedPrevious||index>0&&row.sequence!==rows[index-1].sequence+1n);return{valid:broken.length===0,count:rows.length,firstSequence:rows[0]?.sequence??null,lastSequence:rows.at(-1)?.sequence??null,brokenIds:broken.map(row=>row.id)}}
export async function buildAuditExport(id:string){const job=await db.auditExport.findUniqueOrThrow({where:{id}});if(job.status==="COMPLETED")return job;await db.auditExport.update({where:{id},data:{status:"PROCESSING"}});try{const filters=job.filters as {from?:string;to?:string;action?:string},where={workspaceId:job.workspaceId,...(filters.action?{action:{contains:filters.action}}:{}),...(filters.from||filters.to?{createdAt:{...(filters.from?{gte:new Date(filters.from)}:{}),...(filters.to?{lte:new Date(filters.to)}:{})}}:{})};const events=[];let cursor:bigint|undefined;do{const page=await db.auditEvent.findMany({where:{...where,...(cursor?{sequence:{gt:cursor}}:{})},orderBy:{sequence:"asc"},take:1000});events.push(...page);cursor=page.at(-1)?.sequence;if(page.length<1000)break}while(true);const records=events.map(event=>({...event,sequence:event.sequence.toString(),metadata:redactAuditMetadata(event.metadata)}));const payload=job.format==="CSV"?["sequence,createdAt,actorId,action,targetType,targetId,eventHash",...records.map(row=>[row.sequence,row.createdAt.toISOString(),row.actorId??"",row.action,row.targetType,row.targetId??"",row.eventHash].map(value=>`"${String(value).replaceAll('"','""')}"`).join(","))].join("\r\n")+"\r\n":records.map(row=>JSON.stringify(row)).join("\n")+"\n",checksum=createHash("sha256").update(payload).digest("hex"),iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",exportKey(),iv),encrypted=Buffer.concat([cipher.update(payload),cipher.final()]),tag=cipher.getAuthTag(),objectKey=`${job.workspaceId}/${job.id}.enc`;await mkdir(path.dirname(path.join(exportRoot,objectKey)),{recursive:true});await writeFile(path.join(exportRoot,objectKey),Buffer.concat([iv,tag,encrypted]));const manifest={schemaVersion:1,format:job.format,workspaceId:job.workspaceId,recordCount:records.length,firstSequence:records[0]?.sequence??null,lastSequence:records.at(-1)?.sequence??null,checksum,generatedAt:new Date().toISOString()};return db.auditExport.update({where:{id},data:{status:"COMPLETED",objectKey,checksum,manifest,completedAt:new Date()}})}catch(error){await db.auditExport.update({where:{id},data:{status:"FAILED",lastError:String(error).slice(0,500)}});throw error}}
export async function readAuditExport(objectKey:string){const bytes=await readFile(/* turbopackIgnore: true */ path.join(/* turbopackIgnore: true */ exportRoot,objectKey)),iv=bytes.subarray(0,12),tag=bytes.subarray(12,28),decipher=createDecipheriv("aes-256-gcm",exportKey(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()])}
export function auditDownloadSignature(id:string,expires:number){return createHmac("sha256",exportKey()).update(`${id}:${expires}`).digest("base64url")}
export function validAuditDownload(id:string,expires:number,signature:string){if(!Number.isInteger(expires)||expires<=Date.now()/1000)return false;const expected=Buffer.from(auditDownloadSignature(id,expires)),actual=Buffer.from(signature);return expected.length===actual.length&&timingSafeEqual(expected,actual)}
