import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { lookup } from "node:dns/promises";
import type { Prisma } from "@prisma/client";
import { enqueueChat } from "./chat-integrations";

export const WEBHOOK_EVENTS=["issue.created","issue.updated","comment.created","sprint.created","release.created","release.released"] as const;
function key(){const value=process.env.WEBHOOK_ENCRYPTION_SECRET??process.env.SESSION_SECRET;if(!value||value.length<32)throw new Error("WEBHOOK_ENCRYPTION_SECRET or SESSION_SECRET must contain at least 32 characters");return createHash("sha256").update(value).digest()}
export function encryptSecret(secret:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv),encrypted=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString("base64url")}
export function decryptSecret(value:string){const bytes=Buffer.from(value,"base64url"),iv=bytes.subarray(0,12),tag=bytes.subarray(12,28),ciphertext=bytes.subarray(28),decipher=createDecipheriv("aes-256-gcm",key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(ciphertext),decipher.final()]).toString("utf8")}
export function webhookSecret(){return `whsec_${randomBytes(32).toString("base64url")}`}
export function webhookSignature(secret:string,timestamp:string,body:string){return `v1=${createHmac("sha256",secret).update(`${timestamp}.${body}`).digest("hex")}`}
export function verifyWebhookSignature(secret:string,timestamp:string,body:string,provided:string,now=Math.floor(Date.now()/1000)){if(!/^\d+$/.test(timestamp)||Math.abs(now-Number(timestamp))>300)return false;const expected=Buffer.from(webhookSignature(secret,timestamp,body)),actual=Buffer.from(provided);return expected.length===actual.length&&timingSafeEqual(expected,actual)}
export function webhookRetryDelay(attempt:number){return Math.min(3_600_000,1000*2**Math.max(0,attempt-1))}
export function isPrivateAddress(address:string){return address==="::1"||address.startsWith("fc")||address.startsWith("fd")||address.startsWith("fe80")||/^127\.|^10\.|^192\.168\.|^169\.254\.|^0\.|^172\.(1[6-9]|2\d|3[01])\./.test(address)}
export async function validateWebhookUrl(value:unknown){if(typeof value!=="string"||value.length>2048)return null;let url:URL;try{url=new URL(value)}catch{return null}if(url.protocol!=="https:"||url.username||url.password||url.port&&url.port!=="443"||url.hostname==="localhost")return null;const addresses=await lookup(url.hostname,{all:true}).catch(()=>[]);if(!addresses.length||addresses.some(({address})=>isPrivateAddress(address)))return null;return url.toString()}
export async function enqueueWebhook(tx:Prisma.TransactionClient,input:{workspaceId:string;projectId?:string|null;event:string;eventId:string;data:Prisma.InputJsonValue}){const subscriptions=await tx.webhookSubscription.findMany({where:{workspaceId:input.workspaceId,enabled:true,events:{has:input.event},OR:[{projectId:null},{projectId:input.projectId??undefined}]},select:{id:true}});if(subscriptions.length)await tx.webhookDelivery.createMany({data:subscriptions.map(({id})=>({subscriptionId:id,eventId:input.eventId,event:input.event,payload:{id:input.eventId,type:input.event,apiVersion:"v1",createdAt:new Date().toISOString(),data:input.data}})),skipDuplicates:true});await enqueueChat(tx,input)}
