import { authenticateScim, parseScimFilter, scimBase, scimError, scimGroup, scimLog, scimPage, scimResponse, SCIM_LIST_SCHEMA } from "@/lib/scim";
import { db } from "@/lib/db";

const include = { members: { include: { scimIdentity: { include: { user: true } } }, orderBy: { scimIdentityId: "asc" as const } } };
export async function GET(request:Request,{params}:{params:Promise<{organization:string}>}){const{organization}=await params;const auth=await authenticateScim(request,organization,"groups:read");if(auth.error)return auth.error;try{const filter=parseScimFilter(new URL(request.url).searchParams.get("filter"),["displayName","externalId"]);const where={organizationId:auth.organizationId,...(filter?{[filter.attribute]:filter.value}:{})};const page=scimPage(request.url);const[totalResults,groups]=await Promise.all([db.organizationGroup.count({where}),db.organizationGroup.findMany({where,include,orderBy:{id:"asc"},skip:page.skip,take:page.count})]);const base=scimBase(request,organization);return scimResponse({schemas:[SCIM_LIST_SCHEMA],totalResults,startIndex:page.startIndex,itemsPerPage:groups.length,Resources:groups.map(group=>scimGroup(group,base))})}catch{return scimError(400,"The filter is invalid.","invalidFilter")}}

export async function POST(request:Request,{params}:{params:Promise<{organization:string}>}){const{organization}=await params;const auth=await authenticateScim(request,organization,"groups:write");if(auth.error)return auth.error;const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const displayName=typeof body?.displayName==="string"?body.displayName.trim():"";const externalId=typeof body?.externalId==="string"&&body.externalId.trim()?body.externalId.trim().slice(0,500):null;const memberIds=Array.isArray(body?.members)?[...new Set(body.members.map(item=>item&&typeof item==="object"?String((item as Record<string,unknown>).value??""):"").filter(Boolean))]:[];if(!displayName||displayName.length>100)return scimError(400,"displayName is required.","invalidValue");const existing=await db.organizationGroup.findFirst({where:{organizationId:auth.organizationId,OR:[{displayName},...(externalId?[{externalId}]:[])]},include});const base=scimBase(request,organization);if(existing){if(existing.displayName===displayName&&existing.externalId===externalId)return scimResponse(scimGroup(existing,base));return scimError(409,"A group with that name or externalId exists.","uniqueness")}
  const members=memberIds.length?await db.scimIdentity.findMany({where:{organizationId:auth.organizationId,id:{in:memberIds},active:true},select:{id:true}}):[];if(members.length!==memberIds.length)return scimError(400,"Every member must be an active user in this organization.","invalidValue");
  try{const group=await db.organizationGroup.create({data:{organizationId:auth.organizationId,displayName,externalId,members:{create:members.map(item=>({scimIdentityId:item.id}))}},include});await scimLog(auth.organizationId,auth.token.id,"create","Group",group.id,201,undefined,{memberCount:members.length});return scimResponse(scimGroup(group,base),201,{location:`${base}/Groups/${group.id}`,etag:`W/\"${group.version}\"`})}catch{return scimError(409,"The group conflicts with an existing resource.","uniqueness")}}
