import { NextResponse } from "next/server";
import { getAuthContext } from "@/lib/auth";
import { db } from "@/lib/db";
import { organizationAdmin } from "@/lib/enterprise-organization";

async function access(id:string){const context=await getAuthContext();if(!context)return{error:NextResponse.json({error:"Authentication required."},{status:401})};const admin=await organizationAdmin(context.workspace.id,context.user.id);if(!admin)return{error:NextResponse.json({error:"Organization administration is required."},{status:403})};const group=await db.organizationGroup.findFirst({where:{id,organizationId:admin.organizationId}});if(!group)return{error:NextResponse.json({error:"Organization group not found."},{status:404})};return{context,admin,group}}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const result=await access(id);if(result.error)return result.error;const mappings=await db.scimGroupMapping.findMany({where:{groupId:id},orderBy:{createdAt:"asc"}});return NextResponse.json({mappings})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const result=await access(id);if(result.error)return result.error;const{context,admin}=result;const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const workspaceId=typeof body?.workspaceId==="string"?body.workspaceId:"";const projectId=typeof body?.projectId==="string"&&body.projectId?body.projectId:null;const role=typeof body?.role==="string"?body.role:"";if(!["VIEWER","MEMBER","ADMIN"].includes(role))return NextResponse.json({error:"A supported role is required."},{status:400});const workspace=await db.workspace.findFirst({where:{id:workspaceId,organizationId:admin.organizationId}});if(!workspace)return NextResponse.json({error:"Workspace is outside this organization."},{status:400});if(projectId&&!await db.project.findFirst({where:{id:projectId,workspaceId}}))return NextResponse.json({error:"Project is outside the selected workspace."},{status:400});try{const mapping=await db.$transaction(async tx=>{const created=await tx.scimGroupMapping.create({data:{groupId:id,workspaceId,projectId,role}});await tx.auditEvent.create({data:{workspaceId:context.workspace.id,actorId:context.user.id,action:"identity.scim_group_mapping.created",targetType:"scim_group_mapping",targetId:created.id,metadata:{groupId:id,workspaceId,projectId,role}}});return created});return NextResponse.json({mapping},{status:201})}catch{return NextResponse.json({error:"That mapping already exists."},{status:409})}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const result=await access(id);if(result.error)return result.error;const{context}=result;const mappingId=new URL(request.url).searchParams.get("mappingId");if(!mappingId)return NextResponse.json({error:"mappingId is required."},{status:400});const mapping=await db.scimGroupMapping.findFirst({where:{id:mappingId,groupId:id}});if(!mapping)return NextResponse.json({error:"Mapping not found."},{status:404});await db.$transaction([db.scimGroupMapping.delete({where:{id:mapping.id}}),db.auditEvent.create({data:{workspaceId:context.workspace.id,actorId:context.user.id,action:"identity.scim_group_mapping.deleted",targetType:"scim_group_mapping",targetId:mapping.id,metadata:{groupId:id}}})]);return new NextResponse(null,{status:204})}
