import { NextResponse } from "next/server";
import { getAuthContext } from "@/lib/auth";
import { db } from "@/lib/db";
import { getProjectForContext } from "@/lib/issue-query";

export async function DELETE(_: Request, { params }: { params: Promise<{ key: string; id: string }> }) { const result = await managed(await params); if (result.error) return result.error; const { sprint } = result; if (sprint.state !== "PLANNED" || sprint.issues.length) return NextResponse.json({ error: "Only empty future sprints can be deleted." }, { status: 409 }); await db.sprint.delete({ where: { id: sprint.id } }); return new Response(null, { status: 204 }); }

export async function PATCH(request: Request, { params }: { params: Promise<{ key: string; id: string }> }) {
  const result = await managed(await params); if (result.error) return result.error; const { project, sprint } = result;
  if (sprint.state === "COMPLETED") return NextResponse.json({ error: "Completed sprints are immutable." }, { status: 409 });
  const body = await request.json().catch(() => null) as Record<string, unknown> | null; const action = body?.action; const expectedVersion = Number(body?.version);
  if (!Number.isInteger(expectedVersion) || expectedVersion !== sprint.version) return NextResponse.json({ error: "Sprint changed since it was loaded. Refresh and retry.", version: sprint.version }, { status: 409 });
  try {
    if (action === "edit") { if (sprint.state !== "PLANNED") return conflict("Only future sprints can be edited."); const name = typeof body?.name === "string" ? body.name.trim() : sprint.name; const goal = typeof body?.goal === "string" ? body.goal.trim() : sprint.goal; const startsAt = body?.startsAt === "" ? null : body?.startsAt ? date(body.startsAt) : sprint.startsAt; const endsAt = body?.endsAt === "" ? null : body?.endsAt ? date(body.endsAt) : sprint.endsAt; const capacityTarget = body?.capacityTarget === "" ? null : body?.capacityTarget != null ? integer(body.capacityTarget, 0, 10000) : sprint.capacityTarget; if (!name || name.length > 100 || (goal?.length ?? 0) > 500 || body?.startsAt && !startsAt || body?.endsAt && !endsAt || body?.capacityTarget != null && body.capacityTarget !== "" && capacityTarget == null || startsAt && endsAt && startsAt >= endsAt) return NextResponse.json({ error: "Sprint details are invalid." }, { status: 400 }); await updateVersion(sprint.id, sprint.version, { name, goal: goal || null, startsAt, endsAt, capacityTarget }); }
    else if (action === "move") { if (sprint.state !== "PLANNED" || !["up", "down"].includes(String(body?.direction))) return conflict("Only future sprints can be reordered."); const direction = body?.direction === "up" ? -1 : 1; const neighbor = await db.sprint.findFirst({ where: { projectId: project.id, state: "PLANNED", position: direction < 0 ? { lt: sprint.position } : { gt: sprint.position } }, orderBy: { position: direction < 0 ? "desc" : "asc" } }); if (neighbor) await db.$transaction(async (tx) => { await tx.sprint.update({ where: { id: neighbor.id }, data: { position: sprint.position, version: { increment: 1 } } }); const changed = await tx.sprint.updateMany({ where: { id: sprint.id, version: sprint.version }, data: { position: neighbor.position, version: { increment: 1 } } }); if (changed.count !== 1) throw new Error("CONFLICT"); }); }
    else if (action === "start") { if (sprint.state !== "PLANNED") return conflict("Only planned sprints can start."); await updateVersion(sprint.id, sprint.version, { state: "ACTIVE", startsAt: sprint.startsAt ?? new Date() }); }
    else if (action === "complete") { if (sprint.state !== "ACTIVE") return conflict("Only the active sprint can be completed."); const destination = typeof body?.destination === "string" && body.destination !== "backlog" ? await db.sprint.findFirst({ where: { id: body.destination, projectId: project.id, state: "PLANNED" } }) : null; if (typeof body?.destination === "string" && body.destination !== "backlog" && !destination) return NextResponse.json({ error: "Choose a valid future sprint for unfinished work." }, { status: 400 }); const rows = await db.sprintIssue.findMany({ where: { sprintId: sprint.id }, include: { issue: { include: { status: true } } }, orderBy: { position: "asc" } }); const done = rows.filter(({ issue }) => issue.status.category === "DONE"); const unfinished = rows.filter(({ issue }) => issue.status.category !== "DONE"); await db.$transaction(async (tx) => { await tx.sprintSnapshotIssue.createMany({ data: rows.map(({ issue }) => ({ sprintId: sprint.id, issueId: issue.id, issueKey: `${project.key}-${issue.number}`, summary: issue.summary, estimate: issue.estimate, completed: issue.status.category === "DONE", completedAt: issue.completedAt })) }); if (destination) { const last = await tx.sprintIssue.aggregate({ where: { sprintId: destination.id }, _max: { position: true } }); for (const [index, row] of unfinished.entries()) await tx.sprintIssue.update({ where: { sprintId_issueId: { sprintId: sprint.id, issueId: row.issueId } }, data: { sprintId: destination.id, position: (last._max.position ?? -1) + index + 1 } }); } else await tx.sprintIssue.deleteMany({ where: { sprintId: sprint.id, issueId: { in: unfinished.map(({ issueId }) => issueId) } } }); const changed = await tx.sprint.updateMany({ where: { id: sprint.id, version: sprint.version }, data: { state: "COMPLETED", endsAt: new Date(), completedAt: new Date(), totalIssueCount: rows.length, completedIssueCount: done.length, totalEstimate: rows.reduce((sum, { issue }) => sum + (issue.estimate ?? 0), 0), completedEstimate: done.reduce((sum, { issue }) => sum + (issue.estimate ?? 0), 0), version: { increment: 1 } } }); if (changed.count !== 1) throw new Error("CONFLICT"); }); }
    else if (action === "add" || action === "remove") { const issueId = typeof body?.issueId === "string" ? body.issueId : ""; const issue = await db.issue.findFirst({ where: { id: issueId, projectId: project.id, archivedAt: null }, include: { status: true } }); if (!issue) return NextResponse.json({ error: "Issue not found." }, { status: 404 }); await db.$transaction(async (tx) => { const changed = await tx.sprint.updateMany({ where: { id: sprint.id, version: sprint.version }, data: { version: { increment: 1 } } }); if (changed.count !== 1) throw new Error("CONFLICT"); if (action === "remove") await tx.sprintIssue.deleteMany({ where: { sprintId: sprint.id, issueId } }); else { await tx.sprintIssue.deleteMany({ where: { issueId, sprint: { state: { in: ["PLANNED", "ACTIVE"] } } } }); const last = await tx.sprintIssue.aggregate({ where: { sprintId: sprint.id }, _max: { position: true } }); await tx.sprintIssue.create({ data: { sprintId: sprint.id, issueId, position: (last._max.position ?? -1) + 1 } }); } await tx.issueHistory.create({ data: { workspaceId: project.workspaceId, projectId: project.id, issueId, sprintId: sprint.id, event: action === "add" ? "SPRINT_ADDED" : "SPRINT_REMOVED", statusCategory: issue.status.category, estimate: issue.estimate } }); }); }
    else if (action === "reorder") { const ids = Array.isArray(body?.issueIds) && body.issueIds.every((value) => typeof value === "string") ? body.issueIds as string[] : []; if (!ids.length || new Set(ids).size !== ids.length || await db.sprintIssue.count({ where: { sprintId: sprint.id, issueId: { in: ids } } }) !== ids.length) return NextResponse.json({ error: "Issue order is invalid." }, { status: 400 }); await db.$transaction(async (tx) => { const changed = await tx.sprint.updateMany({ where: { id: sprint.id, version: sprint.version }, data: { version: { increment: 1 } } }); if (changed.count !== 1) throw new Error("CONFLICT"); for (const [position, issueId] of ids.entries()) await tx.sprintIssue.update({ where: { sprintId_issueId: { sprintId: sprint.id, issueId } }, data: { position } }); }); }
    else return NextResponse.json({ error: "Unsupported sprint action." }, { status: 400 });
  } catch (cause) { if ((cause instanceof Error && cause.message === "CONFLICT") || (cause as { code?: string })?.code === "P2002") return conflict("Sprint changed concurrently or another sprint is active."); throw cause; }
  return NextResponse.json({ ok: true });
}

async function managed({ key, id }: { key: string; id: string }) { const context = await getAuthContext(); if (!context) return { error: NextResponse.json({ error: "Authentication required." }, { status: 401 }) }; if (context.role === "VIEWER") return { error: NextResponse.json({ error: "Viewers cannot manage sprints." }, { status: 403 }) }; const project = await getProjectForContext(context, key); const member = await db.projectMember.findUnique({ where: { projectId_userId: { projectId: project.id, userId: context.user.id } } }); if (member?.role === "VIEWER") return { error: NextResponse.json({ error: "Project viewers cannot manage sprints." }, { status: 403 }) }; const sprint = await db.sprint.findFirst({ where: { id, projectId: project.id }, include: { issues: true } }); if (!sprint) return { error: NextResponse.json({ error: "Sprint not found." }, { status: 404 }) }; return { context, project, sprint }; }
async function updateVersion(id: string, version: number, data: Parameters<typeof db.sprint.updateMany>[0]["data"]) { const changed = await db.sprint.updateMany({ where: { id, version }, data: { ...data, version: { increment: 1 } } }); if (changed.count !== 1) throw new Error("CONFLICT"); }
function date(value: unknown) { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null; const result = new Date(`${value}T12:00:00.000Z`); return Number.isNaN(result.getTime()) ? null : result; }
function integer(value: unknown, min: number, max: number) { const result = Number(value); return Number.isInteger(result) && result >= min && result <= max ? result : null; }
function conflict(error: string) { return NextResponse.json({ error }, { status: 409 }); }
