import { NextResponse } from "next/server";
import type { Prisma } from "@prisma/client";
import { getAuthContext } from "@/lib/auth";
import { db } from "@/lib/db";
import { planDependencyInsights, visiblePlan, PlanError } from "@/lib/portfolio-plan";
import { visibleScenario } from "@/lib/planning-scenarios";

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const context = await getAuthContext(); if (!context) return NextResponse.json({ error: "Authentication required." }, { status: 401 }); try { const { id } = await params; await visiblePlan(context, id); return NextResponse.json({ scenarios: await db.planScenario.findMany({ where: { planId: id, archivedAt: null, OR: [{ ownerId: context.user.id }, { shared: true }] }, include: { owner: { select: { id: true, name: true } }, _count: { select: { changes: true, baselines: true, publishes: true } } }, orderBy: { updatedAt: "desc" }, take: 100 }) }); } catch (cause) { const error = cause as PlanError; return NextResponse.json({ error: error.message }, { status: error.status ?? 400 }); } }

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const context = await getAuthContext(); if (!context) return NextResponse.json({ error: "Authentication required." }, { status: 401 }); try { const { id } = await params, plan = await visiblePlan(context, id), body = await request.json().catch(() => null) as Record<string, unknown> | null; if (plan.ownerId !== context.user.id) throw new PlanError("Only the plan owner can create scenarios.", 403); const name = typeof body?.name === "string" ? body.name.trim() : ""; if (!name || name.length > 100) throw new PlanError("Scenario name must contain 1–100 characters."); const clone = typeof body?.cloneFrom === "string" ? await visibleScenario(context, body.cloneFrom) : null; if (clone && clone.planId !== id) throw new PlanError("A scenario can only be cloned within its plan."); const visibleIds = clone ? new Set((await planDependencyInsights(context, id)).nodes.map(node => node.id)) : new Set<string>(), sourceChanges = clone ? await db.scenarioChange.findMany({ where: { scenarioId: clone.id, issueId: { in: [...visibleIds] } } }) : []; const scenario = await db.$transaction(async tx => { const created = await tx.planScenario.create({ data: { planId: id, ownerId: context.user.id, name, description: typeof body?.description === "string" ? body.description.trim().slice(0, 500) : null, shared: body?.shared === true, changes: { create: sourceChanges.map(change => ({ issueId: change.issueId, baseVersion: change.baseVersion, baseSnapshot: change.baseSnapshot as Prisma.InputJsonValue, patch: change.patch as Prisma.InputJsonValue, version: change.version })) } } }); await tx.auditEvent.create({ data: { workspaceId: context.workspace.id, actorId: context.user.id, action: clone ? "scenario.cloned" : "scenario.created", targetType: "plan_scenario", targetId: created.id, metadata: { planId: id, cloneFrom: clone?.id ?? null, copiedChanges: sourceChanges.length } } }); return created; }); return NextResponse.json({ scenario }, { status: 201 }); } catch (cause) { const error = cause as PlanError; return NextResponse.json({ error: error.message }, { status: error.status ?? 400 }); } }
