ALTER TYPE "ProjectTemplate" ADD VALUE 'SERVICE';
CREATE TABLE "PortalGroup" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "position" INTEGER NOT NULL DEFAULT 0, "archivedAt" TIMESTAMP(3), CONSTRAINT "PortalGroup_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PortalGroup_projectId_name_key" ON "PortalGroup"("projectId", "name");
CREATE INDEX "PortalGroup_projectId_position_idx" ON "PortalGroup"("projectId", "position");
CREATE TABLE "ServiceRequestType" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "portalGroupId" TEXT, "issueTypeId" TEXT NOT NULL, "initialStatusId" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "icon" TEXT, "position" INTEGER NOT NULL DEFAULT 0, "draftSchema" JSONB NOT NULL, "draftConsentText" TEXT, "currentVersion" INTEGER NOT NULL DEFAULT 0, "publishedAt" TIMESTAMP(3), "archivedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ServiceRequestType_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ServiceRequestType_projectId_name_key" ON "ServiceRequestType"("projectId", "name");
CREATE INDEX "ServiceRequestType_projectId_archivedAt_position_idx" ON "ServiceRequestType"("projectId", "archivedAt", "position");
CREATE TABLE "ServiceRequestTypeVersion" ("id" TEXT NOT NULL, "requestTypeId" TEXT NOT NULL, "version" INTEGER NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "icon" TEXT, "schema" JSONB NOT NULL, "consentText" TEXT, "publishedById" TEXT NOT NULL, "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ServiceRequestTypeVersion_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ServiceRequestTypeVersion_requestTypeId_version_key" ON "ServiceRequestTypeVersion"("requestTypeId", "version");
CREATE TABLE "ServiceRequest" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "projectId" TEXT NOT NULL, "issueId" TEXT NOT NULL, "requestTypeId" TEXT NOT NULL, "requestTypeVersionId" TEXT NOT NULL, "submittedValues" JSONB NOT NULL, "renderedSchema" JSONB NOT NULL, "consentAcceptedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ServiceRequest_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ServiceRequest_issueId_key" ON "ServiceRequest"("issueId");
CREATE INDEX "ServiceRequest_workspaceId_projectId_requestTypeId_createdAt_idx" ON "ServiceRequest"("workspaceId", "projectId", "requestTypeId", "createdAt");
ALTER TABLE "PortalGroup" ADD CONSTRAINT "PortalGroup_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestType" ADD CONSTRAINT "ServiceRequestType_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestType" ADD CONSTRAINT "ServiceRequestType_portalGroupId_fkey" FOREIGN KEY ("portalGroupId") REFERENCES "PortalGroup"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestType" ADD CONSTRAINT "ServiceRequestType_issueTypeId_fkey" FOREIGN KEY ("issueTypeId") REFERENCES "IssueType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestType" ADD CONSTRAINT "ServiceRequestType_initialStatusId_fkey" FOREIGN KEY ("initialStatusId") REFERENCES "Status"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestTypeVersion" ADD CONSTRAINT "ServiceRequestTypeVersion_requestTypeId_fkey" FOREIGN KEY ("requestTypeId") REFERENCES "ServiceRequestType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "Issue"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_requestTypeId_fkey" FOREIGN KEY ("requestTypeId") REFERENCES "ServiceRequestType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_requestTypeVersionId_fkey" FOREIGN KEY ("requestTypeVersionId") REFERENCES "ServiceRequestTypeVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
