import { expect, test, type Page } from "@playwright/test";

async function signUp(page: Page) { const unique = `sprints-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; await page.goto("/signup"); await page.getByLabel("Your name").fill("Sprint Owner"); await page.getByLabel("Email").fill(`${unique}@example.test`); await page.getByLabel("Password").fill("SecurePlaneo123"); await page.getByLabel("Workspace name").fill("Sprint Workspace"); await page.getByLabel("Workspace URL").fill(unique); await page.getByRole("button", { name: "Create workspace" }).click(); await expect(page).toHaveURL(/\/$/); }
async function api(page: Page, path: string, method = "GET", body?: unknown) { return page.evaluate(async ({ path, method, body }) => { const response = await fetch(path, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const text = await response.text(); return { status: response.status, body: text ? JSON.parse(text) : null }; }, { path, method, body }); }

test("future sprints order deterministically, reject stale writes, and freeze completion totals", async ({ page }) => {
  await signUp(page); const base = "/api/projects/FIRST/sprints";
  const first = await api(page, base, "POST", { name: "Sprint A", goal: "Ship A", startsAt: "2026-09-01", endsAt: "2026-09-14", capacityTarget: 5 }); const second = await api(page, base, "POST", { name: "Sprint B", capacityTarget: 8 }); expect(first.status).toBe(201); expect(second.status).toBe(201);
  let planning = await api(page, base); const sprints = planning.body.sprints as Array<{ id: string; name: string; version: number }>; expect(sprints.filter((value) => value.name.startsWith("Sprint ")).map((value) => value.name)).toEqual(["Sprint A", "Sprint B"]); const a = sprints.find((value) => value.name === "Sprint A")!; const b = sprints.find((value) => value.name === "Sprint B")!;
  expect((await api(page, `${base}/${b.id}`, "PATCH", { action: "move", direction: "up", version: b.version })).status).toBe(200); planning = await api(page, base); expect((planning.body.sprints as Array<{ name: string }>).filter((value) => value.name.startsWith("Sprint ")).map((value) => value.name)).toEqual(["Sprint B", "Sprint A"]);
  const freshA = (planning.body.sprints as Array<{ id: string; name: string; version: number }>).find((value) => value.name === "Sprint A")!; expect((await api(page, `${base}/${freshA.id}`, "PATCH", { action: "edit", goal: "Updated", version: freshA.version })).status).toBe(200); expect((await api(page, `${base}/${freshA.id}`, "PATCH", { action: "edit", goal: "Stale", version: freshA.version })).status).toBe(409);
  const issue = await api(page, "/api/issues", "POST", { projectKey: "FIRST", title: "Sprint snapshot" }); await api(page, `/api/issues/${issue.body.issue.id}`, "PATCH", { estimate: 3 }); planning = await api(page, base); const currentA = (planning.body.sprints as Array<{ id: string; name: string; version: number }>).find((value) => value.name === "Sprint A")!; expect((await api(page, `${base}/${currentA.id}`, "PATCH", { action: "add", issueId: issue.body.issue.id, version: currentA.version })).status).toBe(200);
  planning = await api(page, base); const readyA = (planning.body.sprints as Array<{ id: string; name: string; version: number }>).find((value) => value.name === "Sprint A")!; expect((await api(page, `${base}/${readyA.id}`, "PATCH", { action: "start", version: readyA.version })).status).toBe(200); planning = await api(page, base); const readyB = (planning.body.sprints as Array<{ id: string; name: string; version: number }>).find((value) => value.name === "Sprint B")!; expect((await api(page, `${base}/${readyB.id}`, "PATCH", { action: "start", version: readyB.version })).status).toBe(409);
  const active = (planning.body.sprints as Array<{ id: string; state: string; version: number }>).find((value) => value.state === "ACTIVE")!; expect((await api(page, `${base}/${active.id}`, "PATCH", { action: "complete", destination: readyB.id, version: active.version })).status).toBe(200); planning = await api(page, base); const completed = (planning.body.sprints as Array<{ id: string; totalIssueCount: number; totalEstimate: number }>).find((value) => value.id === active.id)!; expect(completed).toMatchObject({ totalIssueCount: 1, totalEstimate: 3 });
  await api(page, `/api/issues/${issue.body.issue.id}`, "PATCH", { estimate: 8 }); planning = await api(page, base); expect((planning.body.sprints as Array<{ id: string; totalEstimate: number }>).find((value) => value.id === active.id)?.totalEstimate).toBe(3);
});
