import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { createScimSecret, setScimActive } from "@/lib/scim";
import { POST as createUser, GET as listUsers } from "@/app/api/scim/v2/[organization]/Users/route";
import { PATCH as patchUser } from "@/app/api/scim/v2/[organization]/Users/[id]/route";
import { POST as createGroup } from "@/app/api/scim/v2/[organization]/Groups/route";

beforeEach(async()=>{await db.workspace.deleteMany({where:{organization:{slug:{startsWith:"scim-test-"}}}});await db.organization.deleteMany({where:{slug:{startsWith:"scim-test-"}}});await db.rateLimitBucket.deleteMany()});
afterAll(()=>db.$disconnect());
async function fixture(){const nonce=`${Date.now()}-${Math.random()}`;const owner=await db.user.create({data:{email:`scim-owner-${nonce}@example.test`,name:"Owner"}});const organization=await db.organization.create({data:{name:"SCIM",slug:`scim-test-${nonce}`,allowedDomains:[],members:{create:{userId:owner.id,role:"OWNER"}},workspaces:{create:{name:"SCIM",slug:`scim-test-workspace-${nonce}`,memberships:{create:{userId:owner.id,role:"OWNER"}}}}}});const secret=createScimSecret();const token=await db.scimToken.create({data:{organizationId:organization.id,createdById:owner.id,name:"Test",prefix:secret.prefix,secretHash:secret.secretHash,scopes:["users:read","users:write","groups:read","groups:write"]}});return{organization,owner,secret:secret.secret,token}}
function request(url:string,secret:string,method="GET",body?:unknown){return new Request(url,{method,headers:{authorization:`Bearer ${secret}`,...(body?{"content-type":"application/scim+json"}:{})},body:body?JSON.stringify(body):undefined})}

describe("SCIM contract and tenant isolation",()=>{
  it("converges retried creates, filters users, and applies PATCH",async()=>{const{organization,secret}=await fixture();const url=`http://localhost/api/scim/v2/${organization.slug}/Users`;const payload={schemas:["urn:ietf:params:scim:schemas:core:2.0:User"],externalId:"stable-1",userName:`provisioned-${Date.now()}@example.test`,displayName:"Provisioned User",active:true};const first=await createUser(request(url,secret,"POST",payload),{params:Promise.resolve({organization:organization.slug})});expect(first.status).toBe(201);const created=await first.json();const retry=await createUser(request(url,secret,"POST",payload),{params:Promise.resolve({organization:organization.slug})});expect(retry.status).toBe(200);expect((await retry.json()).id).toBe(created.id);const listed=await listUsers(request(`${url}?filter=${encodeURIComponent(`externalId eq \"stable-1\"`)}`,secret),{params:Promise.resolve({organization:organization.slug})});expect((await listed.json()).totalResults).toBe(1);const patched=await patchUser(request(`${url}/${created.id}`,secret,"PATCH",{schemas:["urn:ietf:params:scim:api:messages:2.0:PatchOp"],Operations:[{op:"Replace",path:"displayName",value:"Renamed"}]}),{params:Promise.resolve({organization:organization.slug,id:created.id})});expect(patched.status).toBe(200);expect((await patched.json()).displayName).toBe("Renamed")});

  it("revokes only sessions and memberships inside the deprovisioned organization",async()=>{const{organization}=await fixture();const email=`deprovision-${Date.now()}@example.test`;const user=await db.user.create({data:{email,name:"User"}});const identity=await db.scimIdentity.create({data:{organizationId:organization.id,userId:user.id,userName:email,externalId:"deprovision-stable"},include:{user:true}});const firstWorkspace=await db.workspace.findFirstOrThrow({where:{organizationId:organization.id}});await db.organizationMember.create({data:{organizationId:organization.id,userId:identity.userId,role:"MEMBER"}});await db.workspaceMember.create({data:{workspaceId:firstWorkspace.id,userId:identity.userId,role:"MEMBER"}});const other=await db.organization.create({data:{name:"Other",slug:`scim-test-other-${Date.now()}`,allowedDomains:[],workspaces:{create:{name:"Other",slug:`scim-test-other-workspace-${Date.now()}`}}},include:{workspaces:true}});await db.workspaceMember.create({data:{workspaceId:other.workspaces[0].id,userId:identity.userId,role:"MEMBER"}});const sessions=await Promise.all([db.session.create({data:{userId:identity.userId,workspaceId:firstWorkspace.id,expiresAt:new Date(Date.now()+60000)}}),db.session.create({data:{userId:identity.userId,workspaceId:other.workspaces[0].id,expiresAt:new Date(Date.now()+60000)}})]);await setScimActive(organization.id,identity.id,false);expect((await db.session.findUnique({where:{id:sessions[0].id}}))?.revokedAt).not.toBeNull();expect((await db.session.findUnique({where:{id:sessions[1].id}}))?.revokedAt).toBeNull();expect((await db.workspaceMember.findUnique({where:{workspaceId_userId:{workspaceId:other.workspaces[0].id,userId:identity.userId}}}))?.deactivatedAt).toBeNull()});

  it("rejects cross-organization group members",async()=>{const one=await fixture();const two=await fixture();const email=`foreign-${Date.now()}@example.test`;const user=await db.user.create({data:{email,name:"Foreign"}});const foreign=await db.scimIdentity.create({data:{organizationId:two.organization.id,userId:user.id,userName:email,externalId:"foreign"}});const response=await createGroup(request(`http://localhost/api/scim/v2/${one.organization.slug}/Groups`,one.secret,"POST",{displayName:"Admins",members:[{value:foreign.id}]}),{params:Promise.resolve({organization:one.organization.slug})});expect(response.status).toBe(400);expect(await db.organizationGroup.count({where:{organizationId:one.organization.id}})).toBe(0)});
});
