import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { validateSavedQuery } from "@/lib/saved-filter";
import { consumeRateLimit } from "@/lib/security";
import type { AuthContext } from "@/lib/auth";

beforeEach(async()=>{await db.workspace.deleteMany({where:{slug:{startsWith:"test-"}}});await db.rateLimitBucket.deleteMany()});afterAll(()=>db.$disconnect());
async function fixtures(){const one=await db.workspace.create({data:{name:"Test One",slug:"test-one"}});const two=await db.workspace.create({data:{name:"Test Two",slug:"test-two"}});const user=await db.user.create({data:{name:"Test Owner",email:`owner-${Date.now()}@example.test`,memberships:{create:{workspaceId:one.id,role:"OWNER"}}}});const first=await db.project.create({data:{workspaceId:one.id,name:"First",key:"ONE"}});const foreign=await db.project.create({data:{workspaceId:two.id,name:"Foreign",key:"TWO",visibility:"PRIVATE"}});const context:AuthContext={role:"OWNER",user:{id:user.id,email:user.email,name:user.name,avatarUrl:null,timezone:"UTC",emailNotifications:true,inAppNotifications:true},workspace:{id:one.id,name:one.name,slug:one.slug}};return{one,two,user,first,foreign,context}}
describe("tenant isolation",()=>{it("rejects saved filters that reference another workspace project",async()=>{const{context,first,foreign}=await fixtures();expect(await validateSavedQuery(context,{project:first.key})).toBe(true);expect(await validateSavedQuery(context,{project:foreign.key})).toBe(false)});it("keeps audit queries tenant scoped",async()=>{const{one,two,user}=await fixtures();await db.auditEvent.createMany({data:[{workspaceId:one.id,actorId:user.id,action:"project.created",targetType:"project"},{workspaceId:two.id,action:"identity.login",targetType:"user"}]});const visible=await db.auditEvent.findMany({where:{workspaceId:one.id}});expect(visible).toHaveLength(1);expect(visible[0].action).toBe("project.created")})});
describe("rate limiting",()=>{it("blocks after the configured number of writes",async()=>{expect((await consumeRateLimit("test-client",2,60)).allowed).toBe(true);expect((await consumeRateLimit("test-client",2,60)).allowed).toBe(true);expect((await consumeRateLimit("test-client",2,60)).allowed).toBe(false)})});
