ALTER TABLE "ServiceRequest" ADD COLUMN "slaCheckedAt" TIMESTAMP(3);
CREATE TABLE "SlaCalendar" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE, "name" TEXT NOT NULL, "currentVersion" INTEGER NOT NULL DEFAULT 1);
CREATE UNIQUE INDEX "SlaCalendar_projectId_name_key" ON "SlaCalendar"("projectId","name");
CREATE TABLE "SlaCalendarVersion" ("id" TEXT PRIMARY KEY, "calendarId" TEXT NOT NULL REFERENCES "SlaCalendar"("id") ON DELETE CASCADE ON UPDATE CASCADE, "version" INTEGER NOT NULL, "config" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdById" TEXT NOT NULL);
CREATE UNIQUE INDEX "SlaCalendarVersion_calendarId_version_key" ON "SlaCalendarVersion"("calendarId","version");
CREATE TABLE "SlaGoal" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE, "name" TEXT NOT NULL, "metric" TEXT NOT NULL CHECK ("metric" IN ('RESPONSE','RESOLUTION')), "position" INTEGER NOT NULL DEFAULT 0, "enabled" BOOLEAN NOT NULL DEFAULT true, "currentVersion" INTEGER NOT NULL DEFAULT 1);
CREATE UNIQUE INDEX "SlaGoal_projectId_name_key" ON "SlaGoal"("projectId","name");
CREATE INDEX "SlaGoal_projectId_enabled_position_idx" ON "SlaGoal"("projectId","enabled","position");
CREATE TABLE "SlaGoalVersion" ("id" TEXT PRIMARY KEY, "goalId" TEXT NOT NULL REFERENCES "SlaGoal"("id") ON DELETE CASCADE ON UPDATE CASCADE, "version" INTEGER NOT NULL, "calendarVersionId" TEXT NOT NULL REFERENCES "SlaCalendarVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "targetMinutes" INTEGER NOT NULL CHECK ("targetMinutes" > 0), "riskMinutes" INTEGER NOT NULL CHECK ("riskMinutes" >= 0 AND "riskMinutes" < "targetMinutes"), "conditions" JSONB NOT NULL, "rules" JSONB NOT NULL, "publicLabel" TEXT NOT NULL, "portalVisible" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdById" TEXT NOT NULL);
CREATE UNIQUE INDEX "SlaGoalVersion_goalId_version_key" ON "SlaGoalVersion"("goalId","version");
CREATE TABLE "SlaSignal" ("id" BIGSERIAL PRIMARY KEY, "requestId" TEXT NOT NULL REFERENCES "ServiceRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE, "eventKey" TEXT NOT NULL, "happenedAt" TIMESTAMP(3) NOT NULL, "payload" JSONB NOT NULL, "goalIds" JSONB NOT NULL, "processedAt" TIMESTAMP(3));
CREATE UNIQUE INDEX "SlaSignal_eventKey_key" ON "SlaSignal"("eventKey");
CREATE INDEX "SlaSignal_requestId_processedAt_id_idx" ON "SlaSignal"("requestId","processedAt","id");
CREATE TABLE "SlaCycle" ("id" TEXT PRIMARY KEY, "requestId" TEXT NOT NULL REFERENCES "ServiceRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE, "goalVersionId" TEXT NOT NULL REFERENCES "SlaGoalVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "metric" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "state" TEXT NOT NULL DEFAULT 'RUNNING', "elapsedMs" BIGINT NOT NULL DEFAULT 0, "pauseReasons" JSONB NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL, "lastAt" TIMESTAMP(3) NOT NULL, "endedAt" TIMESTAMP(3), "riskAt" TIMESTAMP(3), "breachedAt" TIMESTAMP(3), "succeededAt" TIMESTAMP(3));
CREATE UNIQUE INDEX "SlaCycle_requestId_metric_sequence_key" ON "SlaCycle"("requestId","metric","sequence");
CREATE INDEX "SlaCycle_requestId_state_idx" ON "SlaCycle"("requestId","state");
CREATE TABLE "SlaEvent" ("id" TEXT PRIMARY KEY, "cycleId" TEXT NOT NULL REFERENCES "SlaCycle"("id") ON DELETE CASCADE ON UPDATE CASCADE, "eventKey" TEXT NOT NULL, "type" TEXT NOT NULL, "happenedAt" TIMESTAMP(3) NOT NULL, "elapsedMs" BIGINT NOT NULL, "metadata" JSONB NOT NULL);
CREATE UNIQUE INDEX "SlaEvent_eventKey_key" ON "SlaEvent"("eventKey");
CREATE INDEX "SlaEvent_cycleId_happenedAt_idx" ON "SlaEvent"("cycleId","happenedAt");
CREATE FUNCTION "reject_sla_history_update"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'SLA history is immutable'; END $$;
CREATE TRIGGER "SlaCalendarVersion_immutable" BEFORE UPDATE ON "SlaCalendarVersion" FOR EACH ROW EXECUTE FUNCTION "reject_sla_history_update"();
CREATE TRIGGER "SlaGoalVersion_immutable" BEFORE UPDATE ON "SlaGoalVersion" FOR EACH ROW EXECUTE FUNCTION "reject_sla_history_update"();
CREATE TRIGGER "SlaEvent_immutable" BEFORE UPDATE ON "SlaEvent" FOR EACH ROW EXECUTE FUNCTION "reject_sla_history_update"();
