CREATE TABLE "Goal" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"ownerId" TEXT NOT NULL,"parentId" TEXT,"name" TEXT NOT NULL,"description" TEXT,"status" TEXT NOT NULL DEFAULT 'ON_TRACK',"visibility" TEXT NOT NULL DEFAULT 'WORKSPACE',"progressMethod" TEXT NOT NULL DEFAULT 'MANUAL',"currentValue" INTEGER NOT NULL DEFAULT 0,"targetValue" INTEGER NOT NULL DEFAULT 100,"periodStart" TIMESTAMP(3) NOT NULL,"periodEnd" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"archivedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Goal_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GoalUpdate" ("id" TEXT NOT NULL,"goalId" TEXT NOT NULL,"authorId" TEXT NOT NULL,"version" INTEGER NOT NULL,"status" TEXT NOT NULL,"progress" INTEGER NOT NULL,"note" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GoalUpdate_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GoalLink" ("id" TEXT NOT NULL,"goalId" TEXT NOT NULL,"targetType" TEXT NOT NULL,"targetId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GoalLink_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Goal_workspaceId_visibility_archivedAt_idx" ON "Goal"("workspaceId","visibility","archivedAt");CREATE INDEX "Goal_ownerId_periodEnd_idx" ON "Goal"("ownerId","periodEnd");CREATE INDEX "Goal_parentId_idx" ON "Goal"("parentId");
CREATE UNIQUE INDEX "GoalUpdate_goalId_version_key" ON "GoalUpdate"("goalId","version");CREATE INDEX "GoalUpdate_goalId_createdAt_idx" ON "GoalUpdate"("goalId","createdAt");
CREATE UNIQUE INDEX "GoalLink_goalId_targetType_targetId_key" ON "GoalLink"("goalId","targetType","targetId");CREATE INDEX "GoalLink_targetType_targetId_idx" ON "GoalLink"("targetType","targetId");
ALTER TABLE "Goal" ADD CONSTRAINT "Goal_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;ALTER TABLE "Goal" ADD CONSTRAINT "Goal_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "Goal" ADD CONSTRAINT "Goal_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Goal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GoalUpdate" ADD CONSTRAINT "GoalUpdate_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal"("id") ON DELETE CASCADE ON UPDATE CASCADE;ALTER TABLE "GoalUpdate" ADD CONSTRAINT "GoalUpdate_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GoalLink" ADD CONSTRAINT "GoalLink_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal"("id") ON DELETE CASCADE ON UPDATE CASCADE;
