import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { releaseAccess, releaseDates, releaseView } from "@/lib/releases";

const include = { issues: { include: { issue: { select: { id: true, number: true, summary: true, estimate: true, archivedAt: true, dueDate: true, status: { select: { name: true, category: true } } } } }, orderBy: { addedAt: "asc" as const } } } as const;

export async function GET(_: Request, { params }: { params: Promise<{ key: string; id: string }> }) { const values = await params; const access = await releaseAccess(values.key); if (access.error) return access.error; const release = await db.release.findFirst({ where: { id: values.id, projectId: access.project.id }, include }); if (!release) return NextResponse.json({ error: "Release not found." }, { status: 404 }); return NextResponse.json({ release: { ...releaseView(release), issues: release.issues.map(({ issue }) => ({ ...issue, key: `${access.project.key}-${issue.number}` })) }, canManage: access.admin }); }

export async function PATCH(request: Request, { params }: { params: Promise<{ key: string; id: string }> }) {
  const values = await params; const access = await releaseAccess(values.key); if (access.error) return access.error; const { context, project, admin } = access; if (!admin) return NextResponse.json({ error: "Project administration is required." }, { status: 403 });
  const body = await request.json().catch(() => null) as Record<string, unknown> | null; const version = Number(body?.version); if (!Number.isInteger(version) || version < 1) return NextResponse.json({ error: "A current release version is required." }, { status: 400 });
  const current = await db.release.findFirst({ where: { id: values.id, projectId: project.id }, include }); if (!current) return NextResponse.json({ error: "Release not found." }, { status: 404 }); if (current.version !== version) return NextResponse.json({ error: "This release changed. Refresh before trying again.", currentVersion: current.version }, { status: 409 });
  const action = typeof body?.action === "string" ? body.action : "update"; const data: Prisma.ReleaseUpdateInput = { version: { increment: 1 } };
  if ((current.releasedAt && action === "update") || (action === "release" && Array.isArray(body?.issueIds))) return NextResponse.json({ error: "Released history is immutable." }, { status: 409 });
  if (action === "release") { if (current.releasedAt) return NextResponse.json({ error: "This release is already released." }, { status: 409 }); data.status = "RELEASED"; data.releasedAt = new Date(); }
  else if (action === "archive") data.archivedAt = new Date(); else if (action === "restore") data.archivedAt = null;
  else { const name = typeof body?.name === "string" ? body.name.trim() : current.name; const description = typeof body?.description === "string" ? body.description.trim() : current.description; const dates = releaseDates({ startsAt: body?.startsAt ?? current.startsAt?.toISOString().slice(0, 10), releaseDate: body?.releaseDate ?? current.releaseDate?.toISOString().slice(0, 10) }); if (!name || name.length > 80 || description && description.length > 2000 || dates.error) return NextResponse.json({ error: dates.error ?? "Release fields are invalid." }, { status: 400 }); Object.assign(data, { name, description, startsAt: dates.startsAt, releaseDate: dates.releaseDate }); }
  const issueIds = Array.isArray(body?.issueIds) ? [...new Set(body.issueIds.filter((id): id is string => typeof id === "string"))] : null; if (issueIds) { const count = await db.issue.count({ where: { id: { in: issueIds }, projectId: project.id, workspaceId: context.workspace.id } }); if (count !== issueIds.length) return NextResponse.json({ error: "Every release issue must belong to this project." }, { status: 400 }); }
  try { const updated = await db.$transaction(async (tx) => { const result = await tx.release.updateMany({ where: { id: current.id, projectId: project.id, version }, data }); if (!result.count) throw new Error("conflict"); if (issueIds) { await tx.issueRelease.deleteMany({ where: { releaseId: current.id } }); if (issueIds.length) await tx.issueRelease.createMany({ data: issueIds.map((issueId) => ({ releaseId: current.id, issueId })) }); } await tx.auditEvent.create({ data: { workspaceId: context.workspace.id, actorId: context.user.id, action: `release.${action === "update" ? "updated" : action + "d"}`, targetType: "release", targetId: current.id, metadata: { projectId: project.id, version, issueCount: issueIds?.length } } }); return tx.release.findUniqueOrThrow({ where: { id: current.id }, include }); }); return NextResponse.json({ release: { ...releaseView(updated), issues: updated.issues.map(({ issue }) => ({ ...issue, key: `${project.key}-${issue.number}` })) } }); }
  catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return NextResponse.json({ error: "Release names must be unique within this project." }, { status: 409 }); if (error instanceof Error && error.message === "conflict") return NextResponse.json({ error: "This release changed. Refresh before trying again." }, { status: 409 }); throw error; }
}
