import { NextResponse } from "next/server";
import { getAuthContext } from "@/lib/auth";
import { db } from "@/lib/db";
import { introducesCycle, validateDependencyInput } from "@/lib/dependency-graph";
import { issueSecurityWhere, requireProjectPermission } from "@/lib/permissions";
import { accessibleProjectWhere } from "@/lib/project-query";
import { createIssueNotifications } from "@/lib/notifications";

async function sourceAccess(id:string){const context=await getAuthContext();if(!context)return {error:NextResponse.json({error:"Authentication required."},{status:401})};const issue=await db.issue.findFirst({where:{id,workspaceId:context.workspace.id,archivedAt:null,project:{is:accessibleProjectWhere(context)},AND:[await issueSecurityWhere(context)]},select:{id:true,projectId:true,number:true,summary:true,project:{select:{key:true}}}});if(!issue)return {error:NextResponse.json({error:"Issue not found."},{status:404})};return {context,issue};}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,result=await sourceAccess(id);if(result.error)return result.error;const{context}=result,security=await issueSecurityWhere(context);const links=await db.issueLink.findMany({where:{OR:[{outwardIssueId:id,inwardIssue:{workspaceId:context.workspace.id,archivedAt:null,project:{is:accessibleProjectWhere(context)},AND:[security]}},{inwardIssueId:id,outwardIssue:{workspaceId:context.workspace.id,archivedAt:null,project:{is:accessibleProjectWhere(context)},AND:[security]}}]},include:{outwardIssue:{select:{id:true,number:true,summary:true,project:{select:{key:true,name:true}}}},inwardIssue:{select:{id:true,number:true,summary:true,project:{select:{key:true,name:true}}}}},orderBy:{createdAt:"asc"},take:200});return NextResponse.json({links:links.map(link=>({...link,outwardIssue:{...link.outwardIssue,key:`${link.outwardIssue.project.key}-${link.outwardIssue.number}`},inwardIssue:{...link.inwardIssue,key:`${link.inwardIssue.project.key}-${link.inwardIssue.number}`}}))});}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,result=await sourceAccess(id);if(result.error)return result.error;const{context,issue}=result;if(!await requireProjectPermission(context,issue.projectId,"issue.edit"))return NextResponse.json({error:"Issue not found."},{status:404});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;try{const input=validateDependencyInput(body),targetId=typeof body?.targetIssueId==="string"?body.targetIssueId:"",target=targetId?await db.issue.findFirst({where:{id:targetId,workspaceId:context.workspace.id,archivedAt:null,project:{is:accessibleProjectWhere(context)},AND:[await issueSecurityWhere(context)]},select:{id:true,assigneeId:true,number:true,summary:true,project:{select:{key:true}}}}):null;if(!target)return NextResponse.json({error:"Target issue not found."},{status:404});if(input.type==="blocks"){const existing=await db.issueLink.findMany({where:{type:"blocks",outwardIssue:{workspaceId:context.workspace.id}},select:{outwardIssueId:true,inwardIssueId:true}});if(introducesCycle(existing.map(edge=>({fromId:edge.outwardIssueId,toId:edge.inwardIssueId})),id,targetId))return NextResponse.json({error:"This dependency would create a cycle. Remove the conflicting path and retry."},{status:409});}
const link=await db.$transaction(async tx=>{const created=await tx.issueLink.create({data:{outwardIssueId:id,inwardIssueId:targetId,type:input.type,lagDays:input.lagDays}});const activity=await tx.issueActivity.create({data:{issueId:id,actorId:context.user.id,action:"dependency.created",changes:{linkId:created.id,type:created.type,lagDays:created.lagDays,targetIssueId:target.id}}});await tx.auditEvent.create({data:{workspaceId:context.workspace.id,actorId:context.user.id,action:"dependency.created",targetType:"issue_link",targetId:created.id,metadata:{outwardIssueId:id,inwardIssueId:target.id,type:created.type,lagDays:created.lagDays}}});if(target.assigneeId)await createIssueNotifications(tx,{workspaceId:context.workspace.id,issueId:target.id,issueKey:`${target.project.key}-${target.number}`,issueTitle:target.summary,actorId:context.user.id,eventId:activity.id,type:"ISSUE_UPDATED",recipientIds:[target.assigneeId]});return created;});return NextResponse.json({link},{status:201});}catch(cause){const message=cause instanceof Error?cause.message:"Dependency could not be created.";return NextResponse.json({error:message.includes("Unique constraint")?"That link already exists.":message},{status:message.includes("already exists")?409:400});}}
