import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { getAuthContext } from "@/lib/auth";
import { db } from "@/lib/db";
import { encodeCsv, ISSUE_CSV_COLUMNS, parseCsv, type IssueCsvRow } from "@/lib/csv";
import { getProjectForContext } from "@/lib/issue-query";

const MAX_BYTES = Number(process.env.CSV_IMPORT_MAX_BYTES ?? 5 * 1024 * 1024);
const MAX_ROWS = Number(process.env.CSV_IMPORT_MAX_ROWS ?? 5000);
type ErrorRow = { row: number; field: string; message: string };

async function access(key: string) {
  const context = await getAuthContext(); if (!context) return { error: NextResponse.json({ error: "Authentication required." }, { status: 401 }) };
  const project = await getProjectForContext(context, key).catch(() => null); if (!project) return { error: NextResponse.json({ error: "Project not found." }, { status: 404 }) };
  const membership = await db.projectMember.findUnique({ where: { projectId_userId: { projectId: project.id, userId: context.user.id } }, select: { role: true } });
  return { context, project, role: membership?.role ?? (context.role === "OWNER" || context.role === "ADMIN" ? "ADMIN" : project.visibility === "PUBLIC" ? "VIEWER" : null) };
}

export async function GET(request: Request, { params }: { params: Promise<{ key: string }> }) {
  const result = await access((await params).key); if (result.error) return result.error; const { context, project, role } = result;
  if (!role) return NextResponse.json({ error: "Project access is required." }, { status: 403 });
  const url = new URL(request.url); if (url.searchParams.get("format") === "template") return csvResponse(encodeCsv([{ externalId: "sample-1", summary: "Example issue", type: "Task", status: "To Do", priority: "MEDIUM" }]), `${project.key}-issue-import-template.csv`);
  const q = url.searchParams.get("q")?.trim(); const status = url.searchParams.get("status"); const assignee = url.searchParams.get("assignee"); const label = url.searchParams.get("label"); const release = url.searchParams.get("release");
  const issues = await db.issue.findMany({ where: { projectId: project.id, workspaceId: context.workspace.id, archivedAt: null, ...(q ? { OR: [{ summary: { contains: q, mode: "insensitive" } }, { description: { string_contains: q } }] } : {}), ...(status ? { status: { name: status } } : {}), ...(assignee ? { assignee: { email: assignee } } : {}), ...(label ? { labels: { some: { label: { name: label } } } } : {}), ...(release ? { releases: { some: { release: { name: release } } } } : {}) }, include: { issueType: true, status: true, assignee: true, labels: { include: { label: true } }, releases: { include: { release: true } }, parent: { include: { importRecord: true } }, importRecord: true, outwardLinks: { include: { inwardIssue: { include: { importRecord: true } } } } }, orderBy: { number: "asc" } });
  const csv = encodeCsv(issues.map((issue) => ({ externalId: issue.importRecord?.externalId ?? `${project.key}-${issue.number}`, summary: issue.summary, description: typeof issue.description === "string" ? issue.description : JSON.stringify(issue.description ?? ""), type: issue.issueType.name, status: issue.status.name, priority: issue.priority, assigneeEmail: issue.assignee?.email ?? "", labels: issue.labels.map(({ label: value }) => value.name).join(";"), estimate: issue.estimate ?? "", dueDate: issue.dueDate?.toISOString().slice(0, 10) ?? "", parentExternalId: issue.parent?.importRecord?.externalId ?? (issue.parent ? `${project.key}-${issue.parent.number}` : ""), links: issue.outwardLinks.map(({ inwardIssue }) => inwardIssue.importRecord?.externalId ?? `${project.key}-${inwardIssue.number}`).join(";"), releases: issue.releases.map(({ release: value }) => value.name).join(";") })));
  await db.auditEvent.create({ data: { workspaceId: context.workspace.id, actorId: context.user.id, action: "issues.csv_exported", targetType: "project", targetId: project.id, metadata: { rowCount: issues.length, filtered: Boolean(q || status || assignee || label || release) } } });
  return csvResponse(csv, `${project.key}-issues.csv`);
}

export async function POST(request: Request, { params }: { params: Promise<{ key: string }> }) {
  const result = await access((await params).key); if (result.error) return result.error; const { context, project, role } = result;
  if (role !== "ADMIN") return NextResponse.json({ error: "Project administration is required to import issues." }, { status: 403 });
  const body = await request.json().catch(() => null) as { csv?: unknown; dryRun?: unknown; idempotencyKey?: unknown } | null; const csv = typeof body?.csv === "string" ? body.csv : ""; const dryRun = body?.dryRun === true; const idempotencyKey = typeof body?.idempotencyKey === "string" ? body.idempotencyKey.trim() : "";
  if (Buffer.byteLength(csv, "utf8") > MAX_BYTES) return NextResponse.json({ error: `CSV exceeds the ${MAX_BYTES}-byte limit.` }, { status: 413 });
  if (!idempotencyKey || idempotencyKey.length > 128) return NextResponse.json({ error: "An idempotency key of 1–128 characters is required." }, { status: 400 });
  const existingBatch = await db.issueImport.findUnique({ where: { projectId_idempotencyKey: { projectId: project.id, idempotencyKey } } }); if (existingBatch && !dryRun) return NextResponse.json({ imported: existingBatch.rowCount, idempotentReplay: true, importId: existingBatch.id });
  const parsed = parseCsv(csv.replace(/^\uFEFF/, ""), MAX_ROWS); const errors = [...parsed.errors];
  const [types, statuses, members, existingImports, releases] = await Promise.all([db.issueType.findMany({ where: { projectId: project.id } }), db.status.findMany({ where: { projectId: project.id } }), db.projectMember.findMany({ where: { projectId: project.id }, include: { user: true } }), db.importedIssue.findMany({ where: { projectId: project.id }, select: { externalId: true } }), db.release.findMany({ where: { projectId: project.id }, select: { id: true, name: true } })]);
  const externalIds = new Set<string>(); const knownExisting = new Set(existingImports.map(({ externalId }) => externalId));
  parsed.rows.forEach((row, index) => { validateRow(row, index + 2, { errors, externalIds, knownExisting, types, statuses, members }); for (const name of row.releases.split(";").map(value => value.trim()).filter(Boolean)) if (!releases.some(release => release.name.toLowerCase() === name.toLowerCase())) errors.push({ row: index + 2, field: "releases", message: `Unknown project release: ${name}.` }); });
  parsed.rows.forEach((row, index) => { const rowNumber = index + 2; if (row.parentExternalId && (!externalIds.has(row.parentExternalId) || row.parentExternalId === row.externalId)) errors.push({ row: rowNumber, field: "parentExternalId", message: "Parent must reference a different row in this file." }); for (const linked of row.links.split(";").map((value) => value.trim()).filter(Boolean)) if (!externalIds.has(linked) || linked === row.externalId) errors.push({ row: rowNumber, field: "links", message: "Links must reference different rows in this file." }); });
  if (errors.length) return NextResponse.json({ valid: false, rowCount: parsed.rows.length, errors }, { status: 422 });
  const digest = createHash("sha256").update(csv).digest("hex");
  if (dryRun) return NextResponse.json({ valid: true, dryRun: true, rowCount: parsed.rows.length, digest, columns: ISSUE_CSV_COLUMNS });
  const imported = await db.$transaction(async (tx) => {
    const batch = await tx.issueImport.create({ data: { projectId: project.id, idempotencyKey, rowCount: parsed.rows.length, createdById: context.user.id } }); const created = new Map<string, string>();
    for (const row of parsed.rows) { const sequence = await tx.project.update({ where: { id: project.id }, data: { issueSequence: { increment: 1 } }, select: { issueSequence: true } }); const type = types.find((value) => value.name.toLowerCase() === row.type.toLowerCase())!; const status = statuses.find((value) => value.name.toLowerCase() === row.status.toLowerCase())!; const assignee = members.find(({ user }) => user.email.toLowerCase() === row.assigneeEmail.toLowerCase()); const issue = await tx.issue.create({ data: { workspaceId: context.workspace.id, projectId: project.id, number: sequence.issueSequence, issueTypeId: type.id, statusId: status.id, reporterId: context.user.id, assigneeId: assignee?.userId, summary: row.summary, description: row.description || "", priority: normalizePriority(row.priority), estimate: row.estimate ? Number(row.estimate) : null, dueDate: row.dueDate ? new Date(`${row.dueDate}T12:00:00.000Z`) : null, rank: `i${sequence.issueSequence.toString().padStart(10, "0")}`, labels: { create: row.labels.split(";").map((value) => value.trim()).filter(Boolean).map((name) => ({ label: { connectOrCreate: { where: { workspaceId_name: { workspaceId: context.workspace.id, name } }, create: { workspaceId: context.workspace.id, name, color: "#6558d7" } } } })) } } }); await tx.importedIssue.create({ data: { projectId: project.id, externalId: row.externalId, issueId: issue.id, importId: batch.id } }); created.set(row.externalId, issue.id); }
    for (const row of parsed.rows) { const issueId = created.get(row.externalId)!; if (row.parentExternalId) await tx.issue.update({ where: { id: issueId }, data: { parentId: created.get(row.parentExternalId) } }); for (const linked of row.links.split(";").map((value) => value.trim()).filter(Boolean)) await tx.issueLink.create({ data: { outwardIssueId: issueId, inwardIssueId: created.get(linked)!, type: "relates" } }); for (const name of row.releases.split(";").map(value => value.trim()).filter(Boolean)) await tx.issueRelease.create({ data: { issueId, releaseId: releases.find(release => release.name.toLowerCase() === name.toLowerCase())!.id } }); }
    await tx.auditEvent.create({ data: { workspaceId: context.workspace.id, actorId: context.user.id, action: "issues.csv_imported", targetType: "project", targetId: project.id, metadata: { importId: batch.id, rowCount: parsed.rows.length, digest } } }); return batch;
  });
  return NextResponse.json({ imported: parsed.rows.length, idempotentReplay: false, importId: imported.id }, { status: 201 });
}

function validateRow(row: IssueCsvRow, number: number, input: { errors: ErrorRow[]; externalIds: Set<string>; knownExisting: Set<string>; types: { name: string }[]; statuses: { name: string }[]; members: { user: { email: string } }[] }) { const error = (field: string, message: string) => input.errors.push({ row: number, field, message }); if (!row.externalId || row.externalId.length > 100) error("externalId", "A unique externalId of 1–100 characters is required."); else if (input.externalIds.has(row.externalId) || input.knownExisting.has(row.externalId)) error("externalId", "externalId already exists in this project or file."); else input.externalIds.add(row.externalId); if (!row.summary || row.summary.length > 200) error("summary", "Summary must contain 1–200 characters."); if (row.description.length > 20_000) error("description", "Description cannot exceed 20,000 characters."); if (!input.types.some(({ name }) => name.toLowerCase() === row.type.toLowerCase())) error("type", "Type is not configured for this project."); if (!input.statuses.some(({ name }) => name.toLowerCase() === row.status.toLowerCase())) error("status", "Status is not configured for this project."); if (!(["URGENT", "HIGH", "MEDIUM", "LOW"]).includes(row.priority.toUpperCase())) error("priority", "Priority must be URGENT, HIGH, MEDIUM, or LOW."); if (row.assigneeEmail && !input.members.some(({ user }) => user.email.toLowerCase() === row.assigneeEmail.toLowerCase())) error("assigneeEmail", "Assignee is not a member of this project."); if (row.estimate && (!/^\d+$/.test(row.estimate) || Number(row.estimate) > 100)) error("estimate", "Estimate must be a whole number from 0–100."); if (row.dueDate && !/^\d{4}-\d{2}-\d{2}$/.test(row.dueDate)) error("dueDate", "Due date must use YYYY-MM-DD."); }
function normalizePriority(value: string) { return value.toUpperCase() as "URGENT" | "HIGH" | "MEDIUM" | "LOW"; }
function csvResponse(csv: string, fileName: string) { return new Response(csv, { headers: { "content-type": "text/csv; charset=utf-8", "content-disposition": `attachment; filename="${fileName}"`, "x-content-type-options": "nosniff" } }); }
