"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initial tenant-scoped integration data is loaded from the API */
import { useEffect, useState } from "react";
type Connection = { id: string; provider: string; name: string; channelName: string; events: string[]; enabled: boolean; lastError: string | null };
export function ChatIntegrations({ projects }: { projects: Array<{ id: string; name: string; visibility: string }> }) {
  const [connections, setConnections] = useState<Connection[]>([]), [events, setEvents] = useState<string[]>([]), [error, setError] = useState<string | null>(null), [provider, setProvider] = useState("SLACK");
  async function load() { const response = await fetch("/api/integrations/chat"), result = await response.json(); if (response.ok) { setConnections(result.connections); setEvents(result.availableEvents); } else setError(result.error); }
  useEffect(() => { void load(); }, []);
  async function create(form: HTMLFormElement) { const values = new FormData(form), response = await fetch("/api/integrations/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider, name: values.get("name"), channelName: values.get("channel"), endpoint: values.get("endpoint"), projectId: values.get("project") || null, events: values.getAll("events"), detailLevel: values.get("detail") }) }), result = await response.json(); if (!response.ok) return setError(result.error); form.reset(); await load(); }
  async function toggle(item: Connection) { await fetch(`/api/integrations/chat/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !item.enabled }) }); await load(); }
  return <section><h2>Slack and Microsoft Teams</h2><p>Map approved Planeo events to an authorized channel. Endpoints remain encrypted and hidden after saving.</p>{error && <div className="login-error" role="alert">{error}</div>}<form onSubmit={event => { event.preventDefault(); void create(event.currentTarget); }}><select aria-label="Chat provider" value={provider} onChange={event => setProvider(event.target.value)}><option>SLACK</option><option>TEAMS</option></select><input required name="name" aria-label="Integration name" placeholder="Engineering alerts"/><input required name="channel" aria-label="Channel name" placeholder="#engineering"/><input required type="url" name="endpoint" aria-label={`${provider} incoming webhook URL`} placeholder="Encrypted incoming webhook URL"/><select name="project" aria-label="Authorized project"><option value="">Public projects only</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name} · {project.visibility}</option>)}</select><select name="detail" aria-label="Message detail"><option>STANDARD</option><option>MINIMAL</option></select><fieldset><legend>Events</legend>{events.map(value => <label key={value}><input type="checkbox" name="events" value={value} defaultChecked={value === "issue.updated"}/>{value}</label>)}</fieldset><button>Add integration</button></form><div className="admin-list">{connections.map(item => <div key={item.id}><span><strong>{item.provider} · {item.channelName}</strong><small>{item.name} · {item.events.join(", ")}{item.lastError ? ` · ${item.lastError}` : ""}</small></span><button onClick={() => void toggle(item)}>{item.enabled ? "Disable" : "Enable"}</button></div>)}</div></section>;
}
