"use client";
import { useEffect, useState } from "react";
const replyKey = () => Array.from(crypto.getRandomValues(new Uint8Array(16)), byte => byte.toString(16).padStart(2, "0")).join("");
export function CustomerConversation({ issueId, readOnly }: { issueId: string; readOnly: boolean }) {
  const [comments, setComments] = useState<Array<{ id: string; body: string; author: string }>>([]), [available, setAvailable] = useState(false), [body, setBody] = useState(""), [status, setStatus] = useState(""), [busy, setBusy] = useState(false), [key, setKey] = useState(() => replyKey());
  const endpoint = `/api/issues/${issueId}/conversation`;
  useEffect(() => { const controller = new AbortController(); fetch(endpoint, { signal: controller.signal }).then(async response => { if (response.ok) { setAvailable(true); setComments((await response.json()).comments); } }).catch(() => undefined); return () => controller.abort(); }, [endpoint]);
  if (!available) return null;
  return <section aria-label="Customer conversation"><h3>Public customer conversation</h3><p>Replies here are visible to authorized customers. The separate Activity comment box adds internal notes.</p>{comments.map(comment => <article key={comment.id}><strong>{comment.author}</strong><p>{comment.body}</p></article>)}{!readOnly && <form onSubmit={async event => { event.preventDefault(); setBusy(true); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "PUBLIC", body, idempotencyKey: key }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setBody(""); setKey(replyKey()); setComments((await fetch(endpoint).then(response => response.json())).comments); setStatus("Public reply saved; email queued for eligible recipients."); } catch (error) { setStatus(error instanceof Error ? error.message : "Reply failed."); } finally { setBusy(false); } }}><label>Public reply to customers<textarea required maxLength={5000} value={body} onChange={event => setBody(event.target.value)} /></label><button disabled={busy}>Send public reply</button></form>}<p role="status">{status}</p></section>;
}
