"use client";
/* eslint-disable react-hooks/set-state-in-effect,react-hooks/exhaustive-deps -- scenario state and loaders follow the selected plan */
import { useEffect, useState } from "react";

type Item = { id: string; key: string; summary: string; dueDate: string | null };
type Scenario = { id: string; name: string; shared: boolean; version: number; _count: { changes: number; baselines: number; publishes: number } };
type Change = { id: string; issueId: string; version: number; baseSnapshot: { dueDate?: string | null }; patch: { dueDate?: string | null } };
type Detail = { scenario: Scenario; changes: Change[]; baselines: Array<{ id: string; name: string; createdAt: string }>; publishes: Array<{ id: string; status: string; createdAt: string }> };

export function PlanningScenarios({ planId, items }: { planId: string; items: Item[] }) {
  const [scenarios, setScenarios] = useState<Scenario[]>([]), [active, setActive] = useState(""), [detail, setDetail] = useState<Detail | null>(null), [name, setName] = useState(""), [issueId, setIssueId] = useState(""), [dueDate, setDueDate] = useState(""), [baseline, setBaseline] = useState(""), [selected, setSelected] = useState<string[]>([]), [status, setStatus] = useState("");
  async function load() { const body = await fetch(`/api/plans/${planId}/scenarios`).then(value => value.json()); setScenarios(body.scenarios ?? []); }
  async function loadDetail(id: string) { const body = await fetch(`/api/plans/${planId}/scenarios/${id}`).then(value => value.json()); setDetail(body.scenario ? body : null); setSelected((body.changes ?? []).map((change: Change) => change.id)); }
  useEffect(() => { setActive(""); setDetail(null); void load(); }, [planId]);
  useEffect(() => { if (active) void loadDetail(active); }, [active]);
  async function create() { const response = await fetch(`/api/plans/${planId}/scenarios`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }), body = await response.json(); if (!response.ok) return setStatus(body.error); setName(""); setActive(body.scenario.id); await load(); }
  async function saveChange() { if (!active || !issueId || !dueDate) return; const existing = detail?.changes.find(change => change.issueId === issueId), response = await fetch(`/api/plans/${planId}/scenarios/${active}/changes`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ issueId, version: existing?.version, patch: { dueDate } }) }), body = await response.json(); if (!response.ok) return setStatus(body.error); setDueDate(""); setStatus("Proposed change saved. Live work is unchanged."); await Promise.all([load(), loadDetail(active)]); }
  async function createBaseline() { if (!active) return; const response = await fetch(`/api/plans/${planId}/scenarios/${active}/baselines`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: baseline }) }), body = await response.json(); if (!response.ok) return setStatus(body.error); setBaseline(""); setStatus("Immutable baseline captured."); await loadDetail(active); }
  async function publish() { if (!active) return; const response = await fetch(`/api/plans/${planId}/scenarios/${active}/publish`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ changeIds: selected }) }), body = await response.json(); if (!response.ok) return setStatus(body.error); setStatus(`${body.applied.length} change(s) published; ${body.conflicts.length} conflict(s).`); await loadDetail(active); }
  return <section className="scenario-workbench" aria-labelledby="scenario-heading"><header><div><h2 id="scenario-heading">Planning scenarios</h2><p>Explore alternatives without changing live issues until an authorized publish.</p></div>{active && <a href={`/api/plans/${planId}/scenarios/${active}?format=json`}>Export scenario</a>}</header><div className="scenario-grid"><div><form onSubmit={event => { event.preventDefault(); void create(); }}><label>Scenario name<input required maxLength={100} value={name} onChange={event => setName(event.target.value)} /></label><button>Create scenario</button></form><div className="scenario-list">{scenarios.map(scenario => <button key={scenario.id} aria-pressed={active === scenario.id} onClick={() => setActive(scenario.id)}><strong>{scenario.name}</strong><small>{scenario._count.changes} changes · {scenario._count.baselines} baselines</small></button>)}</div></div><div>{!detail ? <p>Select or create a scenario.</p> : <><h3>{detail.scenario.name}</h3><form onSubmit={event => { event.preventDefault(); void saveChange(); }}><label>Work item<select required value={issueId} onChange={event => setIssueId(event.target.value)}><option value="">Select visible work</option>{items.map(item => <option key={item.id} value={item.id}>{item.key} · {item.summary}</option>)}</select></label><label>Proposed due date<input required type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></label><button>Save proposed change</button></form><div className="scenario-comparison" role="region" aria-label="Live and proposed comparison">{detail.changes.map(change => { const item = items.find(value => value.id === change.issueId); return <label key={change.id}><input type="checkbox" checked={selected.includes(change.id)} onChange={event => setSelected(current => event.target.checked ? [...current, change.id] : current.filter(id => id !== change.id))} /><span><strong>{item?.key ?? "Visible work"}</strong><small>Live: {item?.dueDate ?? "unscheduled"} → Proposed: {change.patch.dueDate?.slice(0, 10) ?? "unchanged"}</small></span></label>; })}</div><form onSubmit={event => { event.preventDefault(); void createBaseline(); }}><label>Baseline name<input required maxLength={100} value={baseline} onChange={event => setBaseline(event.target.value)} /></label><button>Capture baseline</button></form><button className="scenario-publish" disabled={!selected.length} onClick={() => void publish()}>Publish selected changes</button>{detail.baselines.length > 0 && <p><strong>Baselines:</strong> {detail.baselines.map(value => value.name).join(", ")}</p>}{detail.publishes[0] && <p><strong>Latest publish:</strong> {detail.publishes[0].status}</p>}</>}</div></div>{status && <p role="status">{status}</p>}</section>;
}
