"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Profile = { email:string; name:string; avatarUrl:string|null; timezone:string; emailNotifications:boolean; inAppNotifications:boolean };
export function ProfileSettings({ initial, sessionCount }: { initial:Profile; sessionCount:number }) {
  const router=useRouter(); const [profile,setProfile]=useState(initial); const [status,setStatus]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setStatus(null);const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});const result=await response.json() as {error?:string};setStatus(response.ok?'Profile saved.':result.error??'Could not save profile.');setBusy(false);if(response.ok)router.refresh();}
  async function revoke(){if(!window.confirm('Sign out every active session, including this one?'))return;setBusy(true);const response=await fetch('/api/profile/sessions',{method:'DELETE'});if(response.ok){router.replace('/login');router.refresh();}else{setStatus('Could not revoke sessions.');setBusy(false);}}
  return <main className="settings-page"><header><Link href="/">← Back to Planeo</Link><strong>Account settings</strong></header><div className="settings-grid"><form onSubmit={save}><span>PROFILE</span><h1>Your profile</h1><p>Manage the identity and notification preferences shown across your workspace.</p><label>Display name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} required maxLength={100}/></label><label>Email<input value={profile.email} disabled /></label><label>Avatar URL<input type="url" value={profile.avatarUrl??''} onChange={e=>setProfile({...profile,avatarUrl:e.target.value||null})} placeholder="https://…" /></label><label>Time zone<input value={profile.timezone} onChange={e=>setProfile({...profile,timezone:e.target.value})} placeholder="UTC" required /></label><fieldset><legend>Notifications</legend><label><input type="checkbox" checked={profile.emailNotifications} onChange={e=>setProfile({...profile,emailNotifications:e.target.checked})}/> Email notifications</label><label><input type="checkbox" checked={profile.inAppNotifications} onChange={e=>setProfile({...profile,inAppNotifications:e.target.checked})}/> In-app notifications</label></fieldset>{status&&<div className="auth-success">{status}</div>}<button disabled={busy}>{busy?'Saving…':'Save profile'}</button></form><section className="session-card"><span>SECURITY</span><h2>Active sessions</h2><p>You currently have {sessionCount} active {sessionCount===1?'session':'sessions'}. Resetting sessions immediately signs out every browser and device.</p><button disabled={busy} onClick={revoke}>Sign out everywhere</button></section></div></main>;
}
