"use client";

import { BarChart3, CalendarClock } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type Summary = { statuses: Array<{ id: string; name: string; color: string; issueCount: number; estimateTotal: number }>; sprint: { id: string; name: string; goal?: string; endsAt?: string; issueCount: number; completedCount: number; estimateTotal: number; completedEstimate: number } | null; releases: Array<{id:string;name:string;releaseDate?:string;issueCount:number;unresolvedCount:number;estimateTotal:number}>; error?: string };

export function ProjectSummary({ projectKey }: { projectKey: string }) {
  const [data, setData] = useState<Summary | null>(null); const [error, setError] = useState<string | null>(null); const [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/projects/${projectKey}/summary`, { signal: controller.signal }).then(async (response) => { const result = await response.json() as Summary; if (!response.ok) throw new Error(result.error ?? "Project summary could not be loaded."); return result; }).then(setData).catch((cause: Error) => { if (cause.name !== "AbortError") setError(cause.message); }); return () => controller.abort(); }, [projectKey, retry]);
  if (error) return <div className="project-summary-state" role="alert">{error}<button onClick={() => { setError(null); setRetry((value) => value + 1); }}>Retry</button></div>;
  if (!data) return <div className="project-summary-state" role="status">Loading project summary…</div>;
  const total = data.statuses.reduce((sum, status) => sum + status.issueCount, 0);
  return <section className="project-summary-view"><div className="project-summary-cards">{data.statuses.map((status) => <Link key={status.id} href={`/search?project=${projectKey}&status=${status.id}`}><i style={{ background: status.color }} /><span>{status.name}<strong>{status.issueCount}</strong><small>{status.estimateTotal} estimate points</small></span></Link>)}</div>{total === 0 && <div className="project-summary-state">This project has no issues yet.</div>}<div className="project-summary-detail"><section><header><BarChart3 /><div><h2>Delivery status</h2><p>{total} issues across {data.statuses.length} workflow states</p></div></header><div className="summary-status-bar">{data.statuses.map((status) => <i key={status.id} title={`${status.name}: ${status.issueCount}`} style={{ background: status.color, width: total ? `${status.issueCount / total * 100}%` : "0%" }} />)}</div></section><section><header><CalendarClock /><div><h2>Active sprint</h2><p>{data.sprint?.name ?? "No active sprint"}</p></div></header>{data.sprint ? <><strong>{data.sprint.completedCount} of {data.sprint.issueCount} issues complete</strong><div className="summary-progress"><i style={{ width: data.sprint.issueCount ? `${data.sprint.completedCount / data.sprint.issueCount * 100}%` : "0%" }} /></div><small>{data.sprint.completedEstimate} of {data.sprint.estimateTotal} estimate points · {data.sprint.endsAt ? `Ends ${new Date(data.sprint.endsAt).toLocaleDateString()}` : "No end date"}</small></> : <p>Start a sprint from the backlog to track progress here.</p>}</section><section><header><CalendarClock/><div><h2>Upcoming releases</h2><p>{data.releases.length?`${data.releases.length} planned targets`:"No planned releases"}</p></div></header>{data.releases.map(release=><Link key={release.id} href={`/projects/${projectKey}/releases`}><strong>{release.name}</strong><small>{release.unresolvedCount} unresolved · {release.estimateTotal} points{release.releaseDate?` · ${new Date(release.releaseDate).toLocaleDateString()}`:""}</small></Link>)}</section></div></section>;
}
