"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Release = { id:string; name:string; description?:string|null; status:"PLANNED"|"RELEASED"; startsAt?:string|null; releaseDate?:string|null; releasedAt?:string|null; archivedAt?:string|null; version:number; issueCount:number; completedCount:number; unresolvedCount:number; totalEstimate:number; completedEstimate:number; completionPercent:number; overdue:boolean; issues?:Array<{id:string;key:string;summary:string;estimate:number|null;status:{name:string;category:string}}> };
type IssueOption = { id:string; key:string; title:string };

export function ReleasePlanner({projectKey,projectName}:{projectKey:string;projectName:string}) {
  const [releases,setReleases]=useState<Release[]>([]),[archived,setArchived]=useState(false),[canManage,setCanManage]=useState(false),[selected,setSelected]=useState<Release|null>(null),[issues,setIssues]=useState<IssueOption[]>([]),[error,setError]=useState("");
  const [draft,setDraft]=useState({name:"",description:"",startsAt:"",releaseDate:""});
  async function load(){const response=await fetch(`/api/projects/${projectKey}/releases?archived=${archived}`);const result=await response.json();if(!response.ok)return setError(result.error);setReleases(result.releases);setCanManage(result.canManage);setError("");}
  useEffect(()=>{const controller=new AbortController();fetch(`/api/projects/${projectKey}/releases?archived=${archived}`,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);return result}).then(result=>{setReleases(result.releases);setCanManage(result.canManage);setError("")}).catch(cause=>{if(cause.name!=="AbortError")setError(cause.message)});return()=>controller.abort();},[projectKey,archived]);
  useEffect(()=>{fetch(`/api/issues?projectKey=${projectKey}`).then(r=>r.ok?r.json():{issues:[]}).then(r=>setIssues(r.issues));},[projectKey]);
  async function create(event:React.FormEvent){event.preventDefault();const response=await fetch(`/api/projects/${projectKey}/releases`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok)return setError(result.error);setDraft({name:"",description:"",startsAt:"",releaseDate:""});await load();}
  async function open(release:Release){const response=await fetch(`/api/projects/${projectKey}/releases/${release.id}`);const result=await response.json();if(!response.ok)return setError(result.error);setSelected(result.release);}
  async function mutate(action:string,extra:Record<string,unknown>={}){if(!selected)return;const response=await fetch(`/api/projects/${projectKey}/releases/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,version:selected.version,...extra})});const result=await response.json();if(!response.ok)return setError(result.error);setSelected(result.release);await load();}
  return <main className="release-page"><header><Link href={`/projects/${projectKey}`}>← {projectName}</Link><div><strong>Releases</strong><small>Version planning and readiness</small></div></header><section className="release-content"><div className="release-title"><div><span>{projectKey} PROJECT</span><h1>Releases</h1><p>Group issues into delivery targets without changing workflow status.</p></div><label><input type="checkbox" checked={archived} onChange={e=>{setSelected(null);setArchived(e.target.checked)}}/> Archived only</label></div>{error&&<div className="login-error" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}{canManage&&!archived&&<form className="release-create" onSubmit={create}><label>Name<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Start date<input type="date" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>Release date<input type="date" value={draft.releaseDate} onChange={e=>setDraft({...draft,releaseDate:e.target.value})}/></label><label>Description<input maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><button>Create release</button></form>}<div className="release-layout"><section className="release-list" aria-label="Project releases">{!releases.length&&<p className="release-empty">{archived?"No archived releases.":"No releases yet. Create the first delivery target."}</p>}{releases.map(release=><button key={release.id} className={selected?.id===release.id?"active":""} onClick={()=>void open(release)}><span><strong>{release.name}</strong><small>{release.status==="RELEASED"?`Released ${new Date(release.releasedAt!).toLocaleDateString()}`:release.releaseDate?`Target ${new Date(release.releaseDate).toLocaleDateString()}`:"No target date"}</small></span><em className={release.overdue?"overdue":""}>{release.completionPercent}%</em><small>{release.completedCount}/{release.issueCount} complete · {release.unresolvedCount} unresolved · {release.completedEstimate}/{release.totalEstimate} points</small></button>)}</section>{selected&&<ReleaseDetail release={selected} issues={issues} canManage={canManage} onMutate={mutate}/>}</div></section></main>;
}

function ReleaseDetail({release,issues,canManage,onMutate}:{release:Release;issues:IssueOption[];canManage:boolean;onMutate:(action:string,extra?:Record<string,unknown>)=>Promise<void>}){const assigned=new Set(release.issues?.map(({id})=>id));return <aside className="release-detail"><h2>{release.name}</h2><p>{release.description||"No description."}</p>{release.overdue&&<strong className="release-warning">Overdue with unresolved issues</strong>}<dl><div><dt>Status</dt><dd>{release.status.toLowerCase()}</dd></div><div><dt>Completion</dt><dd>{release.completionPercent}%</dd></div><div><dt>Unresolved</dt><dd>{release.unresolvedCount}</dd></div><div><dt>Estimate</dt><dd>{release.completedEstimate}/{release.totalEstimate}</dd></div></dl><h3>Targeted issues</h3>{canManage&&release.status==="PLANNED"&&<select aria-label="Add issue to release" value="" onChange={e=>{if(e.target.value)void onMutate("update",{issueIds:[...assigned,e.target.value]})}}><option value="">Add an issue…</option>{issues.filter(i=>!assigned.has(i.id)).map(i=><option value={i.id} key={i.id}>{i.key} — {i.title}</option>)}</select>}<ul>{release.issues?.map(issue=><li key={issue.id}><Link href={`/projects/${issue.key.split("-")[0]}?issue=${issue.id}`}>{issue.key} {issue.summary}</Link><span>{issue.status.name}{canManage&&release.status==="PLANNED"&&<button aria-label={`Remove ${issue.key}`} onClick={()=>void onMutate("update",{issueIds:[...assigned].filter(id=>id!==issue.id)})}>Remove</button>}</span></li>)}</ul>{canManage&&<div className="release-actions">{release.status==="PLANNED"&&<button onClick={()=>void onMutate("release")}>Mark released</button>}<button onClick={()=>void onMutate(release.archivedAt?"restore":"archive")}>{release.archivedAt?"Restore":"Archive"}</button></div>}</aside>}
