"use client";
import { useEffect, useState } from "react";
type Target = { id?: string; label: string; state: string; remainingMinutes: number; updatedAt: string; sequence?: number; events?: { id: string; type: string; happenedAt: string }[] };
export function SlaTargets({ endpoint, agent = false }: { endpoint: string; agent?: boolean }) {
  const [targets, setTargets] = useState<Target[]>([]), [message, setMessage] = useState("");
  useEffect(() => { const controller = new AbortController(); const refresh = () => fetch(endpoint, { signal: controller.signal }).then(async response => { if (!response.ok) { setTargets([]); return; } const result = await response.json(); setTargets(result.targets ?? []); }).catch(() => undefined); void refresh(); const interval = setInterval(refresh, 30000); return () => { controller.abort(); clearInterval(interval); }; }, [endpoint]);
  if (!targets.length) return null;
  return <section aria-label="Service targets"><h3>Service targets</h3><p>Business time remaining, as of the latest worker update.</p>{targets.map((target, index) => <article key={target.id ?? index}><strong>{target.label}</strong><p>{target.state} · {target.remainingMinutes} business minutes remaining{target.sequence ? ` · Cycle ${target.sequence}` : ""}</p><small>Updated {new Date(target.updatedAt).toLocaleString()}</small>{agent && target.events && <details><summary>Target history</summary><ul>{target.events.map(event => <li key={event.id}>{event.type.replace("sla.", "")} · {new Date(event.happenedAt).toLocaleString()}</li>)}</ul></details>}</article>)}{agent && <form onSubmit={async event => { event.preventDefault(); const form = event.currentTarget, reason = new FormData(form).get("reason"); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event: "agent.replied", reason }) }); const result = await response.json(); setMessage(response.ok ? "Response recorded for SLA processing." : result.error); } catch { setMessage("Response could not be recorded."); } }}><label>How was the customer contacted?<input name="reason" required minLength={10} maxLength={500} /></label><button>Confirm customer response sent</button></form>}<p role="status">{message}</p></section>;
}
