"use client";
import { useEffect, useState } from "react";
type Version = { id: string; version: number; config?: unknown; calendarVersionId?: string; targetMinutes?: number; riskMinutes?: number; conditions?: unknown; rules?: unknown; publicLabel?: string; portalVisible?: boolean };
type Setting = { id: string; name: string; currentVersion: number; metric?: string; position?: number; enabled?: boolean; versions: Version[] };
const calendar = { timezone: "UTC", week: [[], [[540, 1020]], [[540, 1020]], [[540, 1020]], [[540, 1020]], [[540, 1020]], []], holidays: [], exceptions: {} };
export function SlaSettings({ projectKey }: { projectKey: string }) {
  const endpoint = `/api/projects/${projectKey}/sla`;
  const [calendars, setCalendars] = useState<Setting[]>([]), [goals, setGoals] = useState<Setting[]>([]), [message, setMessage] = useState("");
  const [kind, setKind] = useState("calendar"), [editing, setEditing] = useState<Setting | null>(null), [name, setName] = useState("Business hours"), [config, setConfig] = useState(JSON.stringify(calendar, null, 2)), [busy, setBusy] = useState(false);
  useEffect(() => { const controller = new AbortController(); fetch(endpoint, { signal: controller.signal }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setCalendars(result.calendars); setGoals(result.goals); }).catch(error => { if (error.name !== "AbortError") setMessage(error.message); }); return () => controller.abort(); }, [endpoint]);
  function edit(type: string, item: Setting | null) {
    setKind(type); setEditing(item); setName(item?.name ?? (type === "calendar" ? "Business hours" : "Resolution commitment"));
    const version = item?.versions[0];
    setConfig(JSON.stringify(type === "calendar" ? version?.config ?? calendar : { metric: item?.metric ?? "RESOLUTION", position: item?.position ?? 0, enabled: item?.enabled ?? true, calendarVersionId: version?.calendarVersionId ?? calendars[0]?.versions[0]?.id ?? "", targetMinutes: version?.targetMinutes ?? 240, riskMinutes: version?.riskMinutes ?? 30, portalVisible: version?.portalVisible ?? false, publicLabel: version?.publicLabel ?? "Resolution target", conditions: version?.conditions ?? [], rules: version?.rules ?? {} }, null, 2));
  }
  async function save() {
    setBusy(true); setMessage("");
    try {
      const parsed = JSON.parse(config), body = { ...(kind === "calendar" ? { config: parsed } : parsed), kind, name, ...(editing ? { id: editing.id, version: editing.currentVersion } : {}) };
      const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), result = await response.json(); if (!response.ok) throw new Error(result.error);
      const reload = await fetch(endpoint), data = await reload.json(); if (!reload.ok) throw new Error(data.error); setCalendars(data.calendars); setGoals(data.goals); setEditing(null); setMessage(`Version ${result.version} saved. Existing cycles retain their historical versions.`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Configuration could not be saved."); } finally { setBusy(false); }
  }
  return <section className="service-queues"><p>Lower goal order wins for each response/resolution metric. Changes apply to future cycles; existing timers retain their historical calendar and goal versions.</p><div className="queue-toolbar"><button onClick={() => edit("calendar", null)}>New calendar</button><button disabled={!calendars.length} onClick={() => edit("goal", null)}>New goal</button></div>{[["Calendars", calendars, "calendar"], ["Goals", goals, "goal"]].map(([title, items, type]) => <section key={String(title)}><h2>{String(title)}</h2><ul>{(items as Setting[]).map(item => <li key={item.id}><button onClick={() => edit(String(type), item)}>{item.name} · version {item.currentVersion}{item.enabled === false ? " · Disabled" : ""}</button><details><summary>Version history</summary><ul>{item.versions.map(version => <li key={version.id}>Version {version.version} · ID {version.id}<pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{JSON.stringify(version, null, 2)}</pre></li>)}</ul></details></li>)}</ul></section>)}
    <form className="queue-editor" onSubmit={event => { event.preventDefault(); void save(); }}><h2>{editing ? "Publish next" : "Create"} {kind} version</h2><label>Name<input required maxLength={100} value={name} onChange={event => setName(event.target.value)} /></label>{kind === "calendar" ? <p>Use timezone, seven week days (Sunday first), working-minute intervals, holiday dates, and date-keyed exceptions. Split overnight hours across days. DST counts actual minutes, including repeated hours.</p> : <><p>Metric: RESPONSE or RESOLUTION. Set calendarVersionId from the version history above, targetMinutes, riskMinutes, position, enabled, portalVisible, and publicLabel.</p><p>Conditions: {`[{"field":"priority","equals":"HIGH"}]`}. Supported fields: requestTypeId, priority, organizationId, label, statusId, statusCategory, event, field:ID.</p><p>Rules: start, stop, reset, success, resume, and pause reasons such as {`{"pause":[{"id":"waiting","when":[{"field":"statusId","equals":"STATUS_ID"}]}]}`}. Empty rules use response confirmation or completed status as the stop, and reopening as reset. Internal comments never count as customer responses.</p></>}<label>{kind === "calendar" ? "Calendar configuration" : "Goal configuration"}<textarea rows={20} spellCheck={false} value={config} onChange={event => setConfig(event.target.value)} /></label><button disabled={busy}>{busy ? "Saving…" : "Publish version"}</button></form><p role="status">{message}</p></section>;
}
