CREATE TYPE "ServiceRequestSharing" AS ENUM ('PRIVATE', 'PARTICIPANTS', 'ORGANIZATION');
CREATE TYPE "PortalTokenPurpose" AS ENUM ('INVITATION', 'EMAIL_VERIFICATION', 'PASSWORD_RECOVERY');
ALTER TABLE "ServiceRequest" ADD COLUMN "customerReporterId" TEXT, ADD COLUMN "customerOrganizationId" TEXT, ADD COLUMN "sharing" "ServiceRequestSharing" NOT NULL DEFAULT 'PRIVATE';

CREATE TABLE "PortalBranding" ("workspaceId" TEXT NOT NULL, "portalName" TEXT NOT NULL, "helpText" TEXT, "logoUrl" TEXT, "primaryColor" TEXT NOT NULL DEFAULT '#3157d5', "locale" TEXT NOT NULL DEFAULT 'en', "customDomain" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PortalBranding_pkey" PRIMARY KEY ("workspaceId"));
CREATE UNIQUE INDEX "PortalBranding_customDomain_key" ON "PortalBranding"("customDomain");
CREATE TABLE "PortalCustomer" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "issueReporterUserId" TEXT NOT NULL, "email" TEXT NOT NULL, "name" TEXT NOT NULL, "passwordHash" TEXT, "verifiedAt" TIMESTAMP(3), "deactivatedAt" TIMESTAMP(3), "locale" TEXT NOT NULL DEFAULT 'en', "emailNotifications" BOOLEAN NOT NULL DEFAULT true, "enterpriseSubject" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PortalCustomer_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PortalCustomer_issueReporterUserId_key" ON "PortalCustomer"("issueReporterUserId");
CREATE UNIQUE INDEX "PortalCustomer_workspaceId_email_key" ON "PortalCustomer"("workspaceId", "email");
CREATE UNIQUE INDEX "PortalCustomer_workspaceId_enterpriseSubject_key" ON "PortalCustomer"("workspaceId", "enterpriseSubject");
CREATE INDEX "PortalCustomer_workspaceId_deactivatedAt_idx" ON "PortalCustomer"("workspaceId", "deactivatedAt");
CREATE TABLE "PortalCustomerSession" ("id" TEXT NOT NULL, "customerId" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PortalCustomerSession_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PortalCustomerSession_customerId_revokedAt_expiresAt_idx" ON "PortalCustomerSession"("customerId", "revokedAt", "expiresAt");
CREATE INDEX "PortalCustomerSession_workspaceId_expiresAt_idx" ON "PortalCustomerSession"("workspaceId", "expiresAt");
CREATE TABLE "PortalCustomerToken" ("id" TEXT NOT NULL, "customerId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "purpose" "PortalTokenPurpose" NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PortalCustomerToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PortalCustomerToken_tokenHash_key" ON "PortalCustomerToken"("tokenHash");
CREATE INDEX "PortalCustomerToken_customerId_purpose_expiresAt_idx" ON "PortalCustomerToken"("customerId", "purpose", "expiresAt");
CREATE TABLE "CustomerOrganization" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CustomerOrganization_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CustomerOrganization_workspaceId_name_key" ON "CustomerOrganization"("workspaceId", "name");
CREATE INDEX "CustomerOrganization_workspaceId_idx" ON "CustomerOrganization"("workspaceId");
CREATE TABLE "CustomerOrganizationMember" ("organizationId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CustomerOrganizationMember_pkey" PRIMARY KEY ("organizationId","customerId"));
CREATE INDEX "CustomerOrganizationMember_customerId_active_idx" ON "CustomerOrganizationMember"("customerId", "active");
CREATE TABLE "PortalProjectOrganization" ("projectId" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "PortalProjectOrganization_pkey" PRIMARY KEY ("projectId","organizationId"));
CREATE INDEX "PortalProjectOrganization_organizationId_enabled_idx" ON "PortalProjectOrganization"("organizationId", "enabled");
CREATE TABLE "PortalProjectCustomer" ("projectId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "PortalProjectCustomer_pkey" PRIMARY KEY ("projectId","customerId"));
CREATE INDEX "PortalProjectCustomer_customerId_enabled_idx" ON "PortalProjectCustomer"("customerId", "enabled");
CREATE TABLE "ServiceRequestParticipant" ("requestId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ServiceRequestParticipant_pkey" PRIMARY KEY ("requestId","customerId"));
CREATE INDEX "ServiceRequestParticipant_customerId_idx" ON "ServiceRequestParticipant"("customerId");
CREATE TABLE "PortalComment" ("id" TEXT NOT NULL, "requestId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "body" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PortalComment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PortalComment_requestId_createdAt_idx" ON "PortalComment"("requestId", "createdAt");
CREATE TABLE "PortalNotification" ("id" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "requestId" TEXT, "type" TEXT NOT NULL, "message" TEXT NOT NULL, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PortalNotification_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PortalNotification_customerId_readAt_createdAt_idx" ON "PortalNotification"("customerId", "readAt", "createdAt");
CREATE INDEX "ServiceRequest_customerReporterId_createdAt_idx" ON "ServiceRequest"("customerReporterId", "createdAt");
CREATE INDEX "ServiceRequest_customerOrganizationId_sharing_createdAt_idx" ON "ServiceRequest"("customerOrganizationId", "sharing", "createdAt");

ALTER TABLE "PortalBranding" ADD CONSTRAINT "PortalBranding_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalCustomer" ADD CONSTRAINT "PortalCustomer_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalCustomer" ADD CONSTRAINT "PortalCustomer_issueReporterUserId_fkey" FOREIGN KEY ("issueReporterUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PortalCustomerSession" ADD CONSTRAINT "PortalCustomerSession_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalCustomerToken" ADD CONSTRAINT "PortalCustomerToken_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CustomerOrganization" ADD CONSTRAINT "CustomerOrganization_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CustomerOrganizationMember" ADD CONSTRAINT "CustomerOrganizationMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "CustomerOrganization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CustomerOrganizationMember" ADD CONSTRAINT "CustomerOrganizationMember_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalProjectOrganization" ADD CONSTRAINT "PortalProjectOrganization_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalProjectOrganization" ADD CONSTRAINT "PortalProjectOrganization_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "CustomerOrganization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalProjectCustomer" ADD CONSTRAINT "PortalProjectCustomer_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalProjectCustomer" ADD CONSTRAINT "PortalProjectCustomer_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_customerReporterId_fkey" FOREIGN KEY ("customerReporterId") REFERENCES "PortalCustomer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_customerOrganizationId_fkey" FOREIGN KEY ("customerOrganizationId") REFERENCES "CustomerOrganization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestParticipant" ADD CONSTRAINT "ServiceRequestParticipant_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "ServiceRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceRequestParticipant" ADD CONSTRAINT "ServiceRequestParticipant_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalComment" ADD CONSTRAINT "PortalComment_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "ServiceRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalComment" ADD CONSTRAINT "PortalComment_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PortalNotification" ADD CONSTRAINT "PortalNotification_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalNotification" ADD CONSTRAINT "PortalNotification_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "PortalCustomer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PortalNotification" ADD CONSTRAINT "PortalNotification_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "ServiceRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
