import { NextResponse } from "next/server";
import { getAuthContext } from "@/lib/auth";
import { db } from "@/lib/db";
import { planDependencyInsights, PlanError } from "@/lib/portfolio-plan";
import { visibleScenario } from "@/lib/planning-scenarios";

export async function GET(request: Request, { params }: { params: Promise<{ id: string; scenarioId: string }> }) { const context = await getAuthContext(); if (!context) return NextResponse.json({ error: "Authentication required." }, { status: 401 }); try { const { id, scenarioId } = await params, scenario = await visibleScenario(context, scenarioId); if (scenario.planId !== id) throw new PlanError("Scenario not found.", 404); const visibleIds = new Set((await planDependencyInsights(context, id)).nodes.map(node => node.id)), changes = (await db.scenarioChange.findMany({ where: { scenarioId }, orderBy: { updatedAt: "desc" } })).filter(change => visibleIds.has(change.issueId)), [baselines, publishes] = await Promise.all([db.scenarioBaseline.findMany({ where: { scenarioId }, select: { id: true, name: true, createdAt: true, author: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 100 }), db.scenarioPublish.findMany({ where: { scenarioId }, select: { id: true, status: true, appliedChanges: true, conflicts: true, createdAt: true, actor: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 100 })]); if (new URL(request.url).searchParams.get("format") === "json") return new NextResponse(JSON.stringify({ scenario: { id: scenario.id, name: scenario.name, version: scenario.version }, changes, baselines, publishes }, null, 2), { headers: { "content-type": "application/json", "content-disposition": `attachment; filename="${scenario.name.replace(/[^a-z0-9-]+/gi, "-")}-scenario.json"` } }); return NextResponse.json({ scenario, changes, baselines, publishes }); } catch (cause) { const error = cause as PlanError; return NextResponse.json({ error: error.message }, { status: error.status ?? 400 }); } }

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string; scenarioId: string }> }) { const context = await getAuthContext(); if (!context) return NextResponse.json({ error: "Authentication required." }, { status: 401 }); try { const { id, scenarioId } = await params, scenario = await visibleScenario(context, scenarioId), body = await request.json().catch(() => null) as Record<string, unknown> | null; if (scenario.planId !== id) throw new PlanError("Scenario not found.", 404); if (scenario.ownerId !== context.user.id) throw new PlanError("Only the scenario owner can change it.", 403); if (!body || !Number.isInteger(body.version) || body.version !== scenario.version) throw new PlanError("Scenario changed since it was loaded. Refresh and retry.", 409); const archivedAt = body.action === "archive" ? new Date() : undefined, updated = await db.$transaction(async tx => { const result = await tx.planScenario.updateMany({ where: { id: scenarioId, version: scenario.version }, data: { ...(archivedAt ? { archivedAt } : {}), ...(typeof body.name === "string" && body.name.trim() ? { name: body.name.trim().slice(0, 100) } : {}), ...(typeof body.shared === "boolean" ? { shared: body.shared } : {}), version: { increment: 1 } } }); if (!result.count) throw new PlanError("Scenario changed since it was loaded. Refresh and retry.", 409); await tx.auditEvent.create({ data: { workspaceId: context.workspace.id, actorId: context.user.id, action: archivedAt ? "scenario.archived" : "scenario.updated", targetType: "plan_scenario", targetId: scenarioId } }); return tx.planScenario.findUniqueOrThrow({ where: { id: scenarioId } }); }); return NextResponse.json({ scenario: updated }); } catch (cause) { const error = cause as PlanError; return NextResponse.json({ error: error.message }, { status: error.status ?? 400 }); } }
