import { authenticateScim, scimBase, scimError, scimGroup, scimLog, scimResponse } from "@/lib/scim";
import { db } from "@/lib/db";
const include={members:{include:{scimIdentity:{include:{user:true}}},orderBy:{scimIdentityId:"asc" as const}}};
async function find(organizationId:string,id:string){return db.organizationGroup.findFirst({where:{id,organizationId},include})}
export async function GET(request:Request,{params}:{params:Promise<{organization:string;id:string}>}){const{organization,id}=await params;const auth=await authenticateScim(request,organization,"groups:read");if(auth.error)return auth.error;const group=await find(auth.organizationId,id);return group?scimResponse(scimGroup(group,scimBase(request,organization)),200,{etag:`W/\"${group.version}\"`}):scimError(404,"Group not found.")}
async function replace(request:Request,organization:string,id:string,patch:boolean){const auth=await authenticateScim(request,organization,"groups:write");if(auth.error)return auth.error;const current=await find(auth.organizationId,id);if(!current)return scimError(404,"Group not found.");const match=request.headers.get("if-match");if(match&&match!==`W/\"${current.version}\"`)return scimError(412,"The supplied version is stale.","mutability");const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return scimError(400,"A request body is required.","invalidSyntax");let displayName=current.displayName;let externalId=current.externalId;let memberIds=current.members.map(item=>item.scimIdentityId);
  if(patch){const operations=Array.isArray(body.Operations)?body.Operations:[];for(const raw of operations){if(!raw||typeof raw!=="object")continue;const operation=raw as Record<string,unknown>;const op=String(operation.op??"").toLowerCase(),path=String(operation.path??"");if(path==="displayName"&&(op==="replace"||op==="add"))displayName=String(operation.value??"").trim();else if(path==="externalId"&&(op==="replace"||op==="add"))externalId=String(operation.value??"").trim()||null;else if(path==="members"&&Array.isArray(operation.value)){const values=operation.value.map(item=>item&&typeof item==="object"?String((item as Record<string,unknown>).value??""):"").filter(Boolean);memberIds=op==="remove"?memberIds.filter(value=>!values.includes(value)):[...new Set([...memberIds,...values])];}else{const filtered=/^members\[value eq \"([^\"]+)\"\]$/.exec(path);if(op==="remove"&&filtered)memberIds=memberIds.filter(value=>value!==filtered[1]);}}}
  else{displayName=typeof body.displayName==="string"?body.displayName.trim():"";externalId=typeof body.externalId==="string"&&body.externalId.trim()?body.externalId.trim():null;memberIds=Array.isArray(body.members)?[...new Set(body.members.map(item=>item&&typeof item==="object"?String((item as Record<string,unknown>).value??""):"").filter(Boolean))]:[]}
  if(!displayName||displayName.length>100)return scimError(400,"displayName is invalid.","invalidValue");const identities=memberIds.length?await db.scimIdentity.findMany({where:{organizationId:auth.organizationId,id:{in:memberIds},active:true},select:{id:true}}):[];if(identities.length!==memberIds.length)return scimError(400,"Every member must be an active user in this organization.","invalidValue");try{await db.$transaction([db.organizationGroup.update({where:{id},data:{displayName,externalId,version:{increment:1}}}),db.organizationGroupMember.deleteMany({where:{groupId:id}}),...(identities.length?[db.organizationGroupMember.createMany({data:identities.map(item=>({groupId:id,scimIdentityId:item.id}))})]:[])]);const saved=await find(auth.organizationId,id);if(!saved)throw new Error();await scimLog(auth.organizationId,auth.token.id,patch?"patch":"replace","Group",id,200,undefined,{memberCount:memberIds.length});return scimResponse(scimGroup(saved,scimBase(request,organization)),200,{etag:`W/\"${saved.version}\"`})}catch{return scimError(409,"The group update conflicts with another resource.","uniqueness")}}
export async function PUT(request:Request,{params}:{params:Promise<{organization:string;id:string}>}){const{organization,id}=await params;return replace(request,organization,id,false)}
export async function PATCH(request:Request,{params}:{params:Promise<{organization:string;id:string}>}){const{organization,id}=await params;return replace(request,organization,id,true)}
export async function DELETE(request:Request,{params}:{params:Promise<{organization:string;id:string}>}){const{organization,id}=await params;const auth=await authenticateScim(request,organization,"groups:write");if(auth.error)return auth.error;const removed=await db.organizationGroup.deleteMany({where:{id,organizationId:auth.organizationId}});if(!removed.count)return scimError(404,"Group not found.");await scimLog(auth.organizationId,auth.token.id,"delete","Group",id,204);return new Response(null,{status:204})}
